=== polserver/polserver/trunk/docs/docs.polserver.com/pol099/corechanges.dtd
<!ELEMENT ESCRIPT (header,pre)>
<!ELEMENT header (topic,text,datemodified)>
  <!ELEMENT topic  (#PCDATA)>
  <!ELEMENT datemodified (#PCDATA)>
<!ELEMENT version (entry*)>
  <!ATTLIST version name CDATA #REQUIRED>
  <!ELEMENT entry (date,author,change*)>
    <!ELEMENT date (#PCDATA)>
    <!ELEMENT author (#PCDATA)>
    <!ELEMENT change (#PCDATA |br)*>
      <!ATTLIST change type CDATA #REQUIRED>  
      <!ELEMENT br EMPTY>

=== polserver/polserver/docs/docs.polserver.com/pol099/corechanges.xml
<?xml version="1.0"?>
<?xml-stylesheet type="text/xsl" href="corechanges.xslt" ?>
<!DOCTYPE ESCRIPT SYSTEM "corechanges.dtd">
<ESCRIPT>
  <header>
    <topic>Latest Core Changes</topic>
    <datemodified>01/04/2012</datemodified>
  </header>
  <version name="POL099">
  	<entry>
      <date>01-14-2012</date>
      <author>Turley</author>
      <change type="Changed">UnicodespeechEvent additional Member "tokens" if speech has (speech.mul) Tokens, gives array of spoken TokenIDs
      </change>
      <change type="Added">servspecopt.cfg SeperateSpeechTokens=1/0 default 0 when set RegisterForSpeechEvents() and EnableEvents/DisableEvents behave different
      </change>
      <change type="Added">uo:RegisterForSpeechEvents Flags LISTENPT_HEAR_TOKENS,LISTENPT_NO_SPEECH
      </change>
      <change type="Added">SYSEVENT_TOKEN_SPEECH:=0x4000 and SYSEVENT_TOKEN_GHOST_SPEECH:=0x8000 for uo:EnableEvents/DisableEvents
      </change>
      <change type="Note">if SeperateSpeechTokens is set you can control which events you get,<br/>
        for NPCs you only get speech with tokens if you set SYSEVENT_TOKEN_SPEECH/SYSEVENT_TOKEN_GHOST_SPEECH
        and non Token speech with SYSEVENT_SPEECH,SYSEVENT_GHOST_SPEECH<br/>
        for RegisterForSpeechEvents() you get speech with and without Tokens when setting LISTENPT_HEAR_TOKENS and no speech without Tokens
        setting LISTENPT_NO_SPEECH
      </change>
      <change type="Note">Token and nonToken Eventtype is still the same (SYSEVENT_SPEECH)
      </change>
    </entry>
    <entry>
      <date>01-03-2012</date>
      <author>Turley</author>
      <change type="Changed">major rewrite of primitive operators +,-,*,/,...
        major speedup of +=,-=,...
      </change>
      <change type="Added">finally support for +=,-=,*=,/=,%= with objectmembers, like who.resist_fire_mod+=1
      </change>
      <change type="Note">if member would return UnInit or Error it does nothing
        so its like (only faster and atomic):<br/>
        var temp:=who.resist_fire_mod;<br/>
        if (!(TypeOfInt(temp) in {OT_UNINIT,OT_ERROR}))<br/>
        temp+=1;<br/>
        who.resist_fire_mod:=temp;<br/>
        endif
      </change>
    </entry>
    <entry>
      <date>01-02-2012</date>
      <author>Turley</author>
      <change type="Added">XMLFile/XMLNode.removexmlnode(int value)<br/>
        removes node of given index<br/>
        XMLFile/XMLNode.removexmlnode(XmlNode node)<br/>
        removes given node<br/>
        XmlNode.clonenode()<br/>
        since all NodeObjects get destroyed when the corresponding XmlFileObject is destroyed, use this method to store a node for later use.
      </change>
    </entry>
    <entry>
      <date>12-18-2011</date>
      <author>Nando</author>
      <change type="Changed">internal handling of intrinsic weapons' unload.
      </change>
      <change type="Removed">INTRINSIC property from Weapon template in itemdesc.cfg. An error occurs
        if it's set. Some shards might have forgot to set it, which would cause
        damage to intrinsic wrestling weapon. This is now handled automatically.
      </change>
    </entry>
    <entry>
      <date>12-17-2011</date>
      <author>Nando</author>
      <change type="Changed">boats.cfg entries are now "Name Graphic X Y &lt;Z&gt;", where Z is optional and
        defaults to zero.
      </change>
    </entry>
    <entry>
      <date>12-17-2011</date>
      <author>Tomi</author>
      <change type="Added">Support for hued boats, use the normal .color r/w member to change the hue
        Patch Submitted by Agata
      </change>
    </entry>
    <entry>
      <date>12-14-2011</date>
      <author>Tomi</author>
      <change type="Removed">pol.cfg MaxObjtype limit removed, now it accepts up to 0xFFFFFFFF ( 4294967295 )
        but try to keep it as low as possible, default value still 0x20000
      </change>
      <change type="Changed">objtype vectors changed to maps to only reserve as much memory as there are
        itemdesc entries, not reserving memory for up to 4 billions of objtypes.
      </change>
      <change type="Changed">boats.cfg entries changed from "Name Graphic X Y" to "Name Graphic X Y Z"
        because some of the new boat components requires different Z levels than the boat
        itself.
      </change>
    </entry>
    <entry>
      <date>12-13-2011</date>
      <author>Austin</author>
      <change type="Added">Support for destroy scripts on multis.
      </change>
    </entry>
    <entry>
      <date>12-13-2011</date>
      <author>Tomi</author>
      <change type="Added">Support for HSA boats ( no smooth move yet, but now all boats are usable )
      </change>
      <change type="Changed">boat.cfg to support new entries "Rope", "Wheel", "Hull", "Tiller", "Rudder", "Sails", "Storage", "Weaponslot"<br/>
        there can be more than 1 of each entry<br/>
        the old entries "Tillerman", "Hold", "PortGangplankExtended", "PortGangplankRetracted", "StarboarGangplankExtended",        "StarboardGangplankRetracted" support just 1 entry each or the boat members get broken
      </change>
      <change type="Added">ReadOnly members for boats<br/>
        .components returns an array of ItemRefs of all the components on the boat<br/>
        .hull returns an array of ItemRefs of all the hull components on the boat, or empty array if none.<br/>
        .rope returns an array of ItemRefs of all the rope components on the boat, or empty array if none.<br/>
        .wheel returns an array of ItemRefs of all the wheel components on the boat, or empty array if none.<br/>
        .rudder returns an array of ItemRefs of all the rudder components on the boat, or empty array if none.<br/>
        .tiller returns an array of ItemRefs of all the tiller components on the boat, or empty array if none.<br/>
        .sails returns an array of ItemRefs of all the sails components on the boat, or empty array if none.<br/>
        .storage returns an array of ItemRefs of all the storage components on the boat, or empty array if none.<br/>
        .weaponslot returns an array of ItemRefs of all the weaponslot components on the boat, or empty array if none.<br/>
        Changed extobj.cfg to support new entries for all the new boat component types and changed the default value of all entries.<br/>
        extobj.cfg entries with default values:<br/>
        Tillerman=0x1F010<br/>
        Port_Plank=0x1F011<br/>
        Starboard_Plank=0x1F012<br/>
        Hold=0x1F013<br/>
        Rope=0x1F014<br/>
        Wheel=0x1F015<br/>
        Hull=0x1F016<br/>
        Tiller=0x1F017<br/>
        Rudder=0x1F018<br/>
        Sails=0x1F019<br/>
        Storage=0x1F01A<br/>
        Weaponslot=0x1F01B<br/>
        Wrestling=0x1F020<br/>
        Mount=0x1F021<br/>
        Secure_Trade_Container=0x1FF01<br/>
        Wornitems_Container=0x1FF02<br/>
      </change>
      <change type="Note">extobj entries just let you define the objtypes, all of these still have to be defined in itemdescs for boats to work correctly.
      </change>
    </entry>
    <entry>
      <date>12-05-2011</date>
      <author>Tomi</author>
      <change type="Fixed">Door methods .open() and .close() were working opposite what they should.
      </change>
    </entry>
    <entry>
      <date>12-04-2011</date>
      <author>Tomi</author>
      <change type="Fixed">EA broke the prof.txt with the latest clients adding "Evaluating Intelligence" and "Spirit Speak" with spaces that resulted into skillnumber 0xFF and skillvalue 0
      </change>
      <change type="Added">UO::UpdateItem( item );<br/>
        updates the item to every client in range, good to use for example after returning 1 in some packethook and the item get invisible.
      </change>
    </entry>
    <entry>
      <date>12-03-2011</date>
      <author>Tomi</author>
      <change type="Changed">startlocs.cfg readded default values for MapID ( 0 ) and Cliloc ( 1075072 which is the Yew town information )
        Pol doesnt anymore throw an error if these values are missing.
      </change>
    </entry>
    <entry>
      <date>12-01-2011</date>
      <author>Nando</author>
      <change type="Fixed">Client hanging after having his connection refused on login. I recommend testing
        different ways of having a client disconnected, like acct.disable(), .ban() and others.
      </change>
    </entry>
    <entry>
      <date>12-01-2011</date>
      <author>Tomi</author>
      <change type="Changed">Polcfg setting MaxObjtype now limited to max 0xFFFFFF (16777215)
      </change>
      <change type="Note">Try to keep it as low as possible
      </change>
    </entry>
    <entry>
      <date>12-01-2011</date>
      <author>MuadDib</author>
      <change type="Changed">UoClientGeneral.maxskills changed to unsigned short. Few places in loops with it changed to use same for the loop counter.
      </change>
    </entry>
    <entry>
      <date>11-30-2011</date>
      <author>Tomi</author>
      <change type="Fixed">Old style spellbooks.
      </change>
    </entry>
    <entry>
      <date>11-29-2011</date>
      <author>MuadDib</author>
      <change type="Fixed">Fixed a script breaker caused by inserting new TypeOfInt() constants in the middle of the Enum. Moved SQL Types to end of list.
      </change>
      <change type="Added">Added SQL entries to the Basic.EM since were missing.
      </change>
    </entry>
    <entry>
      <date>11-29-2011</date>
      <author>Tomi</author>
      <change type="Added">Opengraphic itemdesc entry for Doors ( optional parameter, no need to define if you dont want to use the built in methods )
      </change>
      <change type="Changed">how built in .open() .close() and .toggle() methods works. The now read the graphic what to open to from itemdesc instead of just checking with &amp; 0x1.
        this makes those methods works for new doors too and not only T2A era doors.
      </change>
