=== polserver/polserver/trunk/docs/docs.polserver.com/pol099/scripttypes.dtd
<!ELEMENT ESCRIPT (fileheader,scripttype*)>
<!ELEMENT fileheader (desc,datemodified)>
  <!ATTLIST fileheader name CDATA #REQUIRED>
  <!ELEMENT desc (#PCDATA)>
  <!ELEMENT datemodified (#PCDATA)>
<!ELEMENT scripttype (prototype, parameter*, return?, schedtype, def_prio, whencalled, wherelives, todefine, explain*, example*, relatedobj*, relatedcfg*, relatedtype*)>
  <!ATTLIST scripttype name CDATA #REQUIRED>
  <!ELEMENT prototype (#PCDATA)>
  <!ELEMENT parameter EMPTY>
  <!ATTLIST parameter name CDATA #REQUIRED>
  <!ATTLIST parameter value CDATA #REQUIRED>
  <!ELEMENT return (#PCDATA)>
  <!ELEMENT schedtype (#PCDATA)>
  <!ELEMENT def_prio (#PCDATA)>
  <!ELEMENT whencalled (#PCDATA)>
  <!ELEMENT wherelives (#PCDATA)>
  <!ELEMENT todefine (#PCDATA)>
  <!ELEMENT explain (#PCDATA | code)*>
    <!ELEMENT code (#PCDATA)>
  <!ELEMENT example (#PCDATA)>
  <!ELEMENT relatedobj (#PCDATA)>
  <!ELEMENT relatedcfg (#PCDATA)>
  <!ELEMENT relatedtype (#PCDATA)>

=== polserver/polserver/docs/docs.polserver.com/pol100/scripttypes.xml
<?xml version='1.0' encoding="iso-8859-1"?>
<?xml-stylesheet type="text/xsl" href="scripttypes.xslt" ?>
<!DOCTYPE ESCRIPT SYSTEM "scripttypes.dtd">
<ESCRIPT>
<fileheader name="POL Script Types">
  <desc>This is a list of all the different script types used in the POL system. Some only pertain to specific objects, and/or specifc events, as described.</desc>
  <datemodified>12/14/2019</datemodified>
</fileheader>


<scripttype name="UseScript">
    <prototype>program usescript(character, item)</prototype>
    <parameter name="character" value="Character Ref"/>
    <parameter name="item" value="Item Ref" />
    <return>Return value ignored</return>
    <schedtype>Normal</schedtype>
    <def_prio>100</def_prio>
    <whencalled>When a client double clicks on an item with a defined use script.</whencalled>
    <wherelives>The 'program' in a .src file, in a package or /scripts/items</wherelives>
    <todefine>In the item's itemdesc.cfg entry, the 'Script' property defines the location of the double-click script. This is in package format ':pkgname:scriptname', or if just 'scriptname' in the same package, or /scripts/items. Also item.usescript is writable in the same format.</todefine>
    <explain>This interactive script is called when a client double clicks on an item. This script is then attached to the character (meaning, no other script may be attached to the character until this script exits or calls Detach()).
             If the itemdesc.cfg entry also defines 'RequiresAttention 1' then using that item will cause the player to unhide. </explain>
    <explain>By default the player needs to have line-of-sight to the item. Use the 'UseRequiresLOS' property in the itemdesc.cfg entry to change this per-item template.</explain>
    <explain>By default ghosts may not use items. Use the 'GhostsCanUse' property in the itemdesc.cfg entry to change this per-item template.</explain>
    <explain>The default maximum distance away from the item to use it is 2 or the defined 'DefaultDoubleclickRange' in servspecopt.cfg. To override this, use the 'DoubleclickRange' property in the itemdesc.cfg entry to change this per-item template.</explain>
    <explain>Can be used to override the default double-click behaviors of Containers, Maps, etc.</explain>
    <explain>Doesn't work with Multis.</explain>
    <example>
use uo;
use util;
program my_example_usescript(character, item)
    PrintTextAbove(item, character.name + " used me!");
    item.color := RandomInt(50);
endprogram</example>
    <relatedobj>Character</relatedobj>
    <relatedobj>Item</relatedobj>
    <relatedcfg>itemdesc.cfg</relatedcfg>
    <relatedcfg>servspecopt.cfg</relatedcfg>
</scripttype>


<scripttype name="WalkOnScript">
    <prototype>program walkonscript(character, item, lastx, lasty, lastz)</prototype>
    <parameter name="character" value="Character Ref"/>
    <parameter name="item" value="Item Ref" />
    <parameter name="lastx" value="Character's previous integer world coordinate" />
    <parameter name="lasty" value="Character's previous integer world coordinate" />
    <parameter name="lastz" value="Character's previous integer world coordinate" />
    <return>Return value ignored</return>
    <schedtype>Normal</schedtype>
    <def_prio>100</def_prio>
    <whencalled>When a character moves onto this item.</whencalled>
    <wherelives>The 'program' in a .src file, in a package or /scripts/items</wherelives>
    <todefine>In the item's itemdesc.cfg entry, the 'WalkOnScript' property defines the location of the walk-on script. This is in package format ':pkgname:scriptname', or if just 'scriptname' in the same package, or /scripts/items.</todefine>
    <explain>This interactive script is called when a client moves on an item (walk or teleports). This script is NOT attached to the character.</explain>
    <explain>Doesn't work with Multis.</explain>
    <example>
use uo;
use util;
program my_example_walkonscript(character, item, lastx, lasty, lastz)
    PrintTextAbove(item, "Ouch! " + character.name + ", don't step on me!");
    MoveItemToLocation( item, lastx, lasty, lastz );
endprogram</example>
    <relatedobj>Character</relatedobj>
    <relatedobj>Item</relatedobj>
    <relatedcfg>itemdesc.cfg</relatedcfg>
</scripttype>


<scripttype name="ControlScript">
    <prototype>program controlscript(item)</prototype>
    <parameter name="item" value="Item Ref" />
    <return>Return value ignored</return>
    <schedtype>Normal</schedtype>
    <def_prio>1</def_prio>
    <whencalled>Immediately after the item is created (includes boot-up).</whencalled>
    <wherelives>The 'program' in a .src file, in a package or /scripts/control</wherelives>
    <todefine>In the item's itemdesc.cfg entry, the 'ControlScript' property defines the location of the control script. This is in package format ':pkgname:scriptname', or if just 'scriptname' in the same package, or /scripts/control.</todefine>
    <explain>This script is called when the item is created and stays attached to the item. Usually control scripts do not exit until the item is destroyed (note, you must handle this yourself). They generally use a loop to process events or do some housecleaning after some sleeping, or wait_for_event.</explain>
    <example>
use uo;
use os;
program my_example_controlscript(item)
    RegisterForSpeechEvents(item, 5);
    var who;
    while(item) //exit loop if item is destroyed
        ev := wait_for_event(120);
        if(ev)
            who := ev.source;
            PrintTextAbove(item, who.name + " said: " + ev.text);
        endif
    endwhile
endprogram</example>
    <relatedobj>Item</relatedobj>
    <relatedcfg>itemdesc.cfg</relatedcfg>
    <relatedtype>AIScript</relatedtype>
</scripttype>


<scripttype name="CreateScript">
    <prototype>program createscript(item)</prototype>
    <parameter name="item" value="Item Ref" />
    <return>If 0, item is destroyed, else item is added to the world.</return>
    <schedtype>Run To Completion</schedtype>
    <def_prio>critical</def_prio>
    <whencalled>While the item is being created (via uo.em create item functions, or by the core).</whencalled>
    <wherelives>The 'program' in a .src file, in a package or /scripts/control</wherelives>
    <todefine>In the item's itemdesc.cfg entry, the 'CreateScript' property defines the location of the create script. This is in package format ':pkgname:scriptname', or if just 'scriptname' in the same package, or /scripts/control.</todefine>
    <explain>This script is called when the item is created. Return 1 to allow the item to be created, 0 to destroy the item.</explain>
    <example>
use uo;
program my_example_createscript(item)
    if(item.x &gt;= 500 &amp;&amp; item.x &lt;= 600)
        print("Item created in illegal location");
        return 0;
    endif
    return 1;
endprogram</example>
    <relatedobj>Item</relatedobj>
    <relatedcfg>itemdesc.cfg</relatedcfg>
    <relatedtype>DestroyScript</relatedtype>
</scripttype>


<scripttype name="DestroyScript">
    <prototype>program destroyscript(item)</prototype>
    <parameter name="item" value="Item Ref" />
    <return>If 1, item is allowed to be destroyed, else it is not destroyed.</return>
    <schedtype>Run To Completion</schedtype>
    <def_prio>critical</def_prio>
    <whencalled>While the item is being destroyed (UO.EM::DestroyItem() or core decay).</whencalled>
    <wherelives>The 'program' in a .src file, in a package or /scripts/control</wherelives>
    <todefine>In the item's itemdesc.cfg entry, the 'DestroyScript' property defines the location of the destroy script. This is in package format ':pkgname:scriptname', or if just 'scriptname' in the same package, or /scripts/control.</todefine>
    <explain>This script is called while the item is being destroyed. Return 1 to allow the item to be destroy, 0 to not allow destruction.</explain>
    <example>
use uo;
program my_example_destroyscript(item)
    var gm_flag := GetObjProperty(item,"GM_FLAG");
    if(gm_flag != error)
        return 0;
    else
        return 1;
    endif
endprogram</example>
    <relatedobj>Item</relatedobj>
    <relatedcfg>itemdesc.cfg</relatedcfg>
</scripttype>


<scripttype name="MethodScript">
    <prototype>exported function methodname(params,...)</prototype>
    <parameter name="item" value="Item Ref" />
    <return>core ignores return value, except for Install() see below</return>
    <schedtype>Install() Run To Completion, methods normal</schedtype>
    <def_prio>Install() critical, methods 1</def_prio>
    <whencalled>When a script calls the method for the item, i.e. item.methodname()</whencalled>
    <wherelives>In a .src file, and MUST BE in a package.</wherelives>
    <todefine>In the item's itemdesc.cfg entry, the 'MethodScript' property defines the location of the create script. This is in package format ':pkgname:scriptname', or if just 'scriptname' in the same package.</todefine>
    <explain>Method Scripts allow new object methods to be defined, and can override built-in methods. For example, you may define a method door.wackymethod() or override door.open().</explain>
    <explain>To enable the exported functions in the script, the 'program' in the file must return 1. This is the 'Install()' program that enables the exported methods.</explain>
    <explain>The exported functions may take any number of parameters</explain>
    <explain>To instead call the built-in methods for an object, preceed the name with an underscore '_'. So if you override door.close(), use door._close() to instead call the built-in version.</explain>
    <example>
// This simple example shows how to override the door.open() method
pkg/.../door/itemdesc.cfg:
Door 0x0675
{
    xmod -1
    ymod +1
    script door
    doortype metal
    MethodScript cdoor.ecl  //note .ecl extension
}

pkg/.../door/cdoor.src:
exported function open( door )
    print( "cdoor::open(" + door.serial + ")" );
    return door._open();
endfunction

program install()
    print( "installing cdoor" );
