=== polserver/polserver/tags/R2013-09-03_099/docs/docs.polserver.com/pol099/configfiles.dtd
<!ELEMENT ESCRIPT (fileheader,cfgfile*)>
<!ELEMENT fileheader (subheader, desc,datemodified)>
  <!ATTLIST fileheader name CDATA #REQUIRED>
  <!ELEMENT subheader (#PCDATA)>
  <!ELEMENT desc (top,list*,bottom)>
    <!ELEMENT top (#PCDATA)>
    <!ELEMENT list (#PCDATA)>
    <!ELEMENT bottom (#PCDATA)>
  <!ELEMENT datemodified (#PCDATA)>
<!ELEMENT cfgfile (location, numberallowed, requiredtostart, requiredby*, purpose, structure, explain*, related*)>
  <!ATTLIST cfgfile name CDATA #REQUIRED>
  <!ELEMENT location (#PCDATA)>
  <!ELEMENT numberallowed (#PCDATA)>
  <!ELEMENT requiredtostart (#PCDATA)>
  <!ELEMENT requiredby (#PCDATA)>
  <!ELEMENT purpose (#PCDATA)>
  <!ELEMENT structure (#PCDATA)>
  <!ELEMENT explain (#PCDATA |br|i)*>
    <!ELEMENT br EMPTY>
    <!ELEMENT i (#PCDATA)>
  <!ELEMENT related (#PCDATA)>

=== polserver/polserver/docs/docs.polserver.com/pol100/configfiles.xml
<?xml version='1.0' encoding="iso-8859-1"?>
<?xml-stylesheet type="text/xsl" href="configfiles.xslt" ?>
<!DOCTYPE ESCRIPT SYSTEM "configfiles.dtd">
<ESCRIPT>
<fileheader name="POL Configuration Files">
    <subheader>This is a list of all the files that are read by or used by the Core. Any other files are used by user scripts and are not listed here.</subheader>
    <desc>
      <top>In the following config file explanations, some punctuation is used to show repetition, arbitrary values, and optional entries:</top>
      <list>No punctuation: text must be the same verbatim.</list>
      <list>enclosed in brackets [ ]: text is an optional entry.</list>
      <list>enclosed in parenthesis ( ): text is an arbitrary value.</list>
      <list>enclosed in curly braces { }: text is the default value.</list>
      <list>elipsis ... : repeat entries are allowed.</list>
      <bottom>This means the punctuation in these cases should NOT be in the actual config files used by POL, they only appear here for information purposes. Exception: curly braces { } are used to define an element in a config file. These must be present in the actual file.</bottom>
    </desc>
    <datemodified>08/31/2024</datemodified>
</fileheader>


<cfgfile name="attributes.cfg">
    <location>Any Package</location>
    <numberallowed>any</numberallowed>
    <requiredtostart>Yes</requiredtostart>
    <requiredby>Core</requiredby>
    <purpose>Defines Attribute names and aliases</purpose>
    <structure>
Attribute (Attribute_Name)
{
    [Alias                      (Alias_Name)]...
    [GetIntrinsicModFunction    (script_name:exported_func_name)]
    [Delay                      (Skill Delay for skills with buttons on Skill Window)]
    [Unhides                    (Unhides on skill use (0/1)]
    [Script                     (Location of script for skills with buttons on Skill Window)]
    [DefaultCap                 (cap in tenth of attribute {default ssopt:DefaultAttributeCap}]
    [DisableCoreChecks          (0/1 {default 0}]
}
[Attribute...]
</structure>
    <explain>Attribute_Name defines the UNIQUE name for this attribute, like 'Cooking', 'Tactics', 'Strength', etc.</explain>
    <explain>Aliases are optional and any number maybe be assigned for each attribute. This way 'STR' may be used in place of 'Strength'</explain>
    <explain>At the LEAST, these attributes must be defined: 'Strength', 'Intelligence', 'Dexterity', 'Parry', and 'Tactics' for use in internal calculations.</explain>
    <explain>GetIntrinsicModFunction returns a value between -30000 and +30000 that is added to the Attribute "base" value to obtain the "effective" value for the attribute. The function is called when UO.EM RecalVitals is called.</explain>
    <explain>DisableCoreChecks if true the core will not check during skill_use ( from skillwindow ) for active skills,active spells, frozen, paralyzed or delay</explain>
    <related>uoclient.cfg</related>
    <related>vitals.cfg</related>
    <related>servspecopt.cfg</related>
</cfgfile>


<cfgfile name="vitals.cfg">
    <location>Any Package</location>
    <numberallowed>any</numberallowed>
    <requiredtostart>Yes</requiredtostart>
    <requiredby>Core</requiredby>
    <purpose>Defines Attribute names and aliases</purpose>
    <structure>
Vital (Vital_Name)
{
    RegenRateFunction   (string scriptname:exported_func_name)
    MaximumFunction     (string scriptname:exported_func_name)
    [Alias              (string Alias_Name)]...
    [DepletedFunction   (string scriptname:exported_func_name)]
    [RegenWhileDead     (integer 0/1 {default 0})]
}
[Vital...]
</structure>
    <explain>Vital_Name defines the UNIQUE name for this vital, like 'Mana', 'Stamina', etc.</explain>
    <explain>Aliases are optional and any number maybe be assigned for each vital. This way 'Hits' may be used in place of 'Life'</explain>
    <explain>At the LEAST, these attributes must be defined: 'Life', 'Stamina', 'Mana' for use in internal calculations.</explain>
    <explain>RegenRateFunction should return value from -30000 to 30000. Regen rates are in 'hundredths of points per minute.' A current regen rate of 100 (1 point per 5 seconds) would therefore be 1200 (12 points per minute)</explain>
    <explain>MaximumFunction should return the maximum value for this vital, an integer in 'hundreths' between 100 and 10000000 (1-100,000)</explain>
    <explain>DepletedFunction gets called once the vital reaches zero, the given parameter is the character reference and the reason with the following values 0: Regenerate, 1: Damage, 2: Movement, 3: Death, 4: Resurrect, 5: Script</explain>
    <related>uoclient.cfg</related>
    <related>attributes.cfg</related>
</cfgfile>


<cfgfile name="uoclient.cfg">
    <location>Any Package</location>
    <numberallowed>1</numberallowed>
    <requiredtostart>Yes</requiredtostart>
    <requiredby>Core</requiredby>
    <purpose>Maps vital and attribute names onto UO Client idioms for character status.</purpose>
    <structure>
General
{
    Strength        (string Strength)
    Intelligence    (string Intelligence)
    Dexterity       (string Dexterity)

    Hits            (string Life)
    Mana            (string Mana)
    Stamina         (string Stamina)
    MaxSkillID      (integer maximum UO client skill ID)
    [MethodScript   (string scriptname)]
}
Protocol
{
    #
    # EnableFlowControlPackets: use the 0x33 (0x00 / 0x01) pause/restart packets.
    # Though OSI seems to no longer send these packets, they seem to help with smoothness,
    # particularly with boat movement.
    # NOTE: causes clients 4.0.0e and newer to fail login
    EnableFlowControlPackets    (integer 0/1)
}
Listener
{
    Port             (int port number 1024..65535)
    KeepClients      (integer 0/1 {default 0})
    Encryption       (string encryption type {default none})
    AOSResistances   (integer 0/1)
    [AllowProxy      (IPaddrr)[/(netmask)]]...
}
[Listener ...]

</structure>
    <explain>The right-hand-side "Strength", "Intelligence", and "Dexterity" are Attribute names that MUST be defined in attributes.cfg. </explain>
    <explain>The right-hand-side "Life", "Mana", and "Stamina" are Vital names that MUST be defined in vitals.cfg.</explain>
    <explain>MaxSkillID allows you to use new client skills, but setting it too high can crash older clients. You must define attributes.cfg/uoskills.cfg entries for each skillID up to MaxSkillID (default 57).</explain>
    <explain>The Protocol and Listener sections are optional. You need at least one Listener to accept client connections.</explain>
    <explain>Encryption: valid values are 'major.minor.build', '2.0.0x', 'ignition', 'uorice', and 'none'.</explain>
    <explain>
        Encryptions 'ignition', 'uorice', and 'none' all mean 'no encryption'.
        If the 'major.minor.build' is given, the encryption key will be calculated for
        that client version.
        Example, '7.0.4' is a listener for client 7.0.4.1 (no patch)
    </explain>
    <explain>Each Listener section allows you to listen for different client encryption types on different ports.
        This means you can listen for "1.26.4" clients on port 5003 and "ignition" clients on port 5555.</explain>
    <explain>KeepClients: if set to 1 clients keep this listener port even after different gameserver select; actually 1 is the old behaviour and 0 the old behaviour of pol.cfg ListenPort</explain>
    <explain>AOSResistances: This flag aids in deciding which version of Armor to send in the StatMsg packets. With this enabled, a client who uses an account with AOS Expansion enabled will see their Physical Resist instead of AR member.</explain>
    <explain>AllowProxy: Expect incoming connection from this network to use proxy protocol v2, connections not using valid proxy protocol v2 will be rejected. This element can be specified multiple times.</explain>
    <explain>MethodScript: General Methodscript for characters Deprecated!</explain>
    <related>attributes.cfg</related>
    <related>pol.cfg</related>
    <related>uoskills.cfg</related>
    <related>vitals.cfg</related>
</cfgfile>


<cfgfile name="uoconvert.cfg">
    <location>root directory only</location>
    <numberallowed>1</numberallowed>
    <requiredtostart>Yes</requiredtostart>
    <requiredby>UOConvert</requiredby>
    <purpose>Defines options for uoconvert. Lists the MultiID of boats, houses and decorations ("stairs"). Defines which ItemIDs are valid mounts.</purpose>
    <structure>
#
# UseNoShoot:         means uoconvert will determine whether or not something blocks LOS by use of
#                     the NoShoot tiledata flag instead of the Blocking tiledata flag.
# LOSThroughWindows:  only matters if UseNoShoot is 1. If LOSThroughWindows is 1, then
#                     items marked as windows in tiledata will not impede LOS.
#
# Both of these options default to false. When UseNoShoot is false, the old method of
# determining sight blocking as being equivalent to ability to pass will be used for LOS.
#
LOSOptions
{
    UseNoShoot        (integer 0/1)
    LOSThroughWindows (integer 0/1)
}

#
# MaxStaticsPerBlock:         max. Amount of Static Items per Block of 8x8x256
#                             it is hard limited to 10000. default is 1000.
#
# WarningStaticsPerBlock:     max. Amount of Static Items per Block of 8x8x256 - just a Warning Level
#                             it is hard limited to 10000. default is 1000.
#
# ShowIllegalGraphicWarning:  show warning if Static with illegal Graphic# found
#                             0 or 1. default is 1.
#
StaticOptions
{
    MaxStaticsPerBlock        (int statics number 0..10000)
    WarningStaticsPerBlock    (int statics number 0..10000)
    ShowIllegalGraphicWarning (integer 0/1)
}

#
# ShowRoofAndPlatformWarning: show warning if Roof and Platform Flag are used at same Tile
#                             0 or 1. default is 1.
#
TileOptions
{
    ShowRoofAndPlatformWarning (integer 0/1)
}

MultiTypes
{
