=== polserver/polserver/docs/docs.polserver.com/pol100/escript.dtd
<!ELEMENT ESCRIPT (fileheader,function*)>
<!ELEMENT fileheader (filedesc, datemodified,constant*)>
  <!ATTLIST fileheader fname CDATA #REQUIRED>
  <!ELEMENT filedesc (#PCDATA)>
  <!ELEMENT datemodified (#PCDATA)>
  <!ELEMENT constant (#PCDATA)> 
  
<!ELEMENT function (prototype, parameter*, explain*, return*, error*, related*, relatedcfg*)>
  <!ATTLIST function name CDATA #REQUIRED>
  <!ELEMENT prototype (#PCDATA)>
  <!ELEMENT parameter EMPTY>
    <!ATTLIST parameter name CDATA #REQUIRED>
    <!ATTLIST parameter value CDATA #REQUIRED>
  <!ELEMENT explain (#PCDATA | code)*>
    <!ELEMENT code (#PCDATA)>
  <!ELEMENT return (#PCDATA)>
  <!ELEMENT error (#PCDATA)>
  <!ELEMENT related (#PCDATA)>
  <!ELEMENT relatedcfg (#PCDATA)>

=== polserver/polserver/docs/docs.polserver.com/pol100/fileem.xml
<?xml version='1.0' encoding="iso-8859-1"?>
<?xml-stylesheet type="text/xsl" href="escript.xslt" ?>
<!DOCTYPE ESCRIPT SYSTEM "escript.dtd">
<ESCRIPT>
  <fileheader fname="File.em">
    <filedesc>File Access functions</filedesc>
    <datemodified>11/10/2019</datemodified>
    <constant>// LogToFile constants</constant>
    <constant>const LOG_DATETIME := 1; // log Core-Style DateTimeStr in front of log entry</constant>
    <constant>//BinaryFile constants</constant>
    <constant>const OPENMODE_IN    := 0x01; // (input) Allow input operations on the stream</constant>
    <constant>const OPENMODE_OUT   := 0x02; // (output) Allow output operations on the stream</constant>
    <constant>const OPENMODE_ATE   := 0x04; // (at end) Set the stream's position indicator to the end of the stream on opening</constant>
    <constant>const OPENMODE_APP   := 0x08; // (append) Set the stream's position indicator to the end of the stream before each output operation</constant>
    <constant>const OPENMODE_TRUNC := 0x10; // (truncate) Any current content is discarded, assuming a length of zero on opening</constant>
    <constant> </constant>
    <constant>const SEEKDIR_BEG := 0x00; // beginning of sequence</constant>
    <constant>const SEEKDIR_CUR := 0x01; // current position within sequence</constant>
    <constant>const SEEKDIR_END := 0x02; // end of sequence</constant>
    <constant> </constant>
    <constant>const LITTLE_ENDIAN := 0x00;</constant>
    <constant>const BIG_ENDIAN    := 0x01;</constant>
    <constant> </constant>
    <constant>// ListDirectory constants</constant>
    <constant>const LISTDIR_LIST_DIRS      := 0x1;</constant>
    <constant>const LISTDIR_DONT_LIST_DIRS := 0x0;</constant>
    <constant>const LISTDIR_NO_FILES       := "";</constant>
    <constant>const LISTDIR_ALL_FILES      := "*";</constant>
  </fileheader>

  <function name="FileExists"> 
    <prototype>FileExists( filename )</prototype>
    <parameter name="filename" value="string" />
    <explain>Checks for the existence of a file based on Filename parameter.</explain>
    <return>1 on success</return>
    <error>"Invalid parameter type"</error>
    <error>"Error in filename descriptor"</error>
    <error>"No parent path traversal please."</error>
    <relatedcfg>fileaccess.cfg</relatedcfg>
  </function>

  <function name="ReadFile"> 
    <prototype>ReadFile( filename )</prototype>
    <parameter name="filename" value="string" />
    <explain>Reads a text file, returning the contents as an array of strings, removing newlines.</explain>
    <explain>By default, no package has any file access rights. To grant access, see config/fileaccess.cfg</explain>
    <return>returns array of strings</return>
    <error>"Invalid parameter type"</error>
    <error>"Error in filename descriptor"</error>
    <error>"No parent path traversal please."</error>
    <error>"Access denied"</error>
    <error>"File not found: X"</error>
    <relatedcfg>fileaccess.cfg</relatedcfg>
  </function>

  <function name="WriteFile"> 
    <prototype>WriteFile( filename, textcontents )</prototype>
    <parameter name="filename" value="string" />
    <parameter name="textcontents" value="array of strings" />
    <explain>Writes a new file to disk, appends newlines, creates file if it does not exist, renames existing file to filename.bak</explain>
    <explain>By default, no package has any file access rights. To grant access, see config/fileaccess.cfg</explain>
    <return>1 or error</return>
    <error>"Invalid parameter type"</error>
    <error>"Error in filename descriptor"</error>
    <error>"No parent path traversal please."</error>
    <error>"Access denied"</error>
    <error>"File not found: X"</error>    
    <error>"Error during write."</error>
    <error>"Unable to remove filenameX: reasonY</error>
    <error>"Unable to rename filenameX: to filenameZ: reasonY</error>
    <relatedcfg>fileaccess.cfg</relatedcfg>
  </function>

  <function name="AppendToFile"> 
    <prototype>AppendToFile( filename, textlines )</prototype>
    <parameter name="filename" value="string" />
    <parameter name="textlines" value="array of strings" />
    <explain>Appends to a text file, adding newlines. Creates file if it does not exist.</explain>
    <explain>By default, no package has any file access rights. To grant access, see config/fileaccess.cfg</explain>
    <return>1 or error</return>
    <error>"Invalid parameter type"</error>
    <error>"Error in filename descriptor"</error>
    <error>"No parent path traversal please."</error>
    <error>"Access denied"</error>
    <error>"Unable to open file: X"</error>    
    <error>"Error during write."</error>
    <relatedcfg>fileaccess.cfg</relatedcfg>
  </function>

  <function name="LogToFile"> 
    <prototype>LogToFile( filename, line, flags := 0 )</prototype>
    <parameter name="filename" value="String" />
    <parameter name="line" value="String" />
    <parameter name="flags" value="Integer" />
    <explain>Appends a single line to a text file, adds newlines, creates file if it does not exist.</explain>
    <explain>By default, no package has any file access rights. To grant access, see config/fileaccess.cfg</explain>
    <explain>file.em constants for flags:
<code>
const LOG_DATETIME := 1; // log Core-Style DateTimeStr in front of log entry</code></explain>
    <return>1 or error</return>
    <error>"Invalid parameter type"</error>
    <error>"Error in filename descriptor"</error>
    <error>"No parent path traversal please."</error>
    <error>"Access denied"</error>
    <error>"Unable to open file: X"</error>    
    <error>"Error during write."</error>
    <relatedcfg>fileaccess.cfg</relatedcfg>
  </function>  

  <function name="OpenBinaryFile"> 
    <prototype>OpenBinaryFile( filename, mode := OPENMODE_IN, endian := LITTLE_ENDIAN )</prototype>
    <parameter name="filename" value="string" />
    <parameter name="mode" value="Integer" />
    <parameter name="endian" value="Integer" />
    <explain>Opens BinaryFile stream</explain>
    <explain>By default, no package has any file access rights. To grant access, see config/fileaccess.cfg</explain>
    <explain>file.em constants for mode:
<code>
const OPENMODE_IN    := 0x01; // (input) Allow input operations on the stream
const OPENMODE_OUT   := 0x02; // (output) Allow output operations on the stream
const OPENMODE_ATE   := 0x04; // (at end) Set the stream's position indicator to the end of the stream on opening
const OPENMODE_APP   := 0x08; // (append) Set the stream's position indicator to the end of the stream before each output operation
const OPENMODE_TRUNC := 0x10; // (truncate) Any current content is discarded, assuming a length of zero on opening
</code></explain>
    <explain>file.em constants for endian:
<code>
const LITTLE_ENDIAN := 0x00;
const BIG_ENDIAN    := 0x01;
</code></explain>
    <return>BinaryFile or error</return>
    <error>"Invalid parameter type"</error>
    <error>"Error in filename descriptor"</error>
    <error>"No parent path traversal please."</error>
    <error>"Access denied"</error>
    <related>BinaryFile</related>
    <relatedcfg>fileaccess.cfg</relatedcfg>
  </function>  

  <function name="CreateDirectory"> 
    <prototype>CreateDirectory( dirname )</prototype>
    <parameter name="dirname" value="string" />
    <explain>Creates directory</explain>
    <return>1 or error</return>
    <error>"Invalid parameter type"</error>
    <error>"Error in dirname descriptor"</error>
    <error>"No parent path traversal please."</error>
    <error>"Directory already exists."</error>
    <error>"Could not create directory."</error>
  </function>

  <function name="ListDirectory"> 
    <prototype>ListDirectory( dirname, extension := LISTDIR_ALL_FILES, listdirs := LISTDIR_DONT_LIST_DIRS )</prototype>
    <parameter name="dirname" value="string" />
    <parameter name="extension" value="string" />
    <parameter name="listdirs" value="Integer" />
    <explain>List directory content</explain>
    <explain>extension param can be extension without "." or file.em constant:
<code>
const LISTDIR_NO_FILES       := "";
const LISTDIR_ALL_FILES      := "*";
</code></explain>
    <explain>file.em constants for listdirs:
<code>
const LISTDIR_LIST_DIRS      := 0x1;
const LISTDIR_DONT_LIST_DIRS := 0x0;
</code></explain>
    <return>array of strings or error</return>
    <error>"Invalid parameter type"</error>
    <error>"Error in dirname descriptor"</error>
    <error>"No parent path traversal please."</error>
    <error>"Directory not found."</error>
  </function> 

  <function name="CreateXmlFile"> 
    <prototype>CreateXMLFile()</prototype>
    <explain>creates an empty XMLFile object</explain>
    <return>XMLFile object or error</return>
    <related>XMLFile</related>
  </function>

  <function name="OpenXmlFile"> 
    <prototype>OpenXMLFile( filename )</prototype>
    <parameter name="filename" value="string" />
    <explain>opens given filename and returns XMLFile object, fileaccess.cfg is checked</explain>
    <return>XMLFile object or error</return>
    <related>XMLFile</related>
    <relatedcfg>fileaccess.cfg</relatedcfg>
  </function>

</ESCRIPT>

=== polserver/polserver/tags/R2013-09-03_099/docs/docs.polserver.com/pol099/polsysem.xml
<?xml version='1.0' encoding="iso-8859-1"?>
<?xml-stylesheet type="text/xsl" href="escript.xslt" ?>
<!DOCTYPE ESCRIPT SYSTEM "escript.dtd">
<ESCRIPT>
  <fileheader fname="POLsys.em">
    <filedesc>Functions to access POL system data.</filedesc>
    <datemodified>11/30/2009</datemodified>
<constant>const MSGLEN_VARIABLE := -1;</constant>
  </fileheader>
    
  <function name="ReloadConfiguration"> 
    <prototype>ReloadConfiguration()</prototype>
    <explain>reloads pol.cfg (most entries), npcdesc.cfg and bannedips.cfg</explain>
    <explain>Linux: HUP signal will cause ReloadConfiguration to be called.</explain>
    <return>1</return>
  </function>

  <function name="Packages"> 
    <prototype>Packages()</prototype>
    <explain>Get an array of "package objects", with "name", "supports_http" and "npcdesc" members. (more info TBD)</explain>
    <return>An array of package objects.</return>
  </function>

  <function name="ReadMillisecondClock"> 
    <prototype>ReadMillisecondClock()</prototype>
    <explain>Returns a long integer of the current millisecond clock. TBD: timebase of clock, saved with server?</explain>
    <return>Current time in milliseconds.</return>
  </function>
  
  <function name="SetSysTrayPopupText">
    <prototype>SetSysTrayPopupText(text)</prototype>
    <parameter name="text" value="String tooltip text for systray icon" />
    <explain>Sets the systray icon's tooltip text (win32 only)</explain>
    <return>1</return>
  </function>
  
  <function name="GetItemDescriptor">
    <prototype>GetItemDescriptor(objtype)</prototype>
    <parameter name="objtype" value="int Objtype OR string ObjtypeName" />
    <explain>Returns a struct of all itemdesc.cfg properties for the objtype.</explain>
    <explain>The keys are the property names, i.e. "Color", "Desc", etc. The values can be String, Integer, Real. The exceptions are "CProps" and "StackingIgnoresCProps". "CProps" is a dictionary where the CProp name is the key, and the value can be any packable type (i.e. array, struct, etc.). "StackingIgnoresCProps" is an array of strings.</explain>
    <explain>Note: Descriptor of Weapon will return MinDamage and MaxDamage calculated from Damage-Dice too.</explain>
    <explain>The primary use of this function is to pass it to any of the item creation functions, and the values in the struct will be used in place of the static itemdesc.cfg values. Use it to assign specific properties to an item during creation, rather than after. This allows easier stacking with existing item stacks.</explain>
    <explain>Note: Not all properties can be assigned per-item, so editing the value in the descriptor struct will not be passed to the new item.
<code>
//For example, to stack with an existing stack with color 0x10 and cprop
use uo;
use polsys;
program testdesc(who,objtype)
    var ret := GetItemDescriptor(CInt(objtype));
    ret.Color := 0x10;
    ret.CProps.insert("blah","1"); //assuming the existing stack have this color and cprop
    ret.StackingIgnoresCProps.append("blingbling");    
    var item := CreateItemInBackpack(who,ret,10);
    if(item)
        print("OK!");
    endif
endprogram</code>
<code>
To print the contents of the struct:
var ret := GetItemDescriptor(objtype);
foreach thing in ret
    print(_thing_iter + ": " + thing);
endforeach</code></explain>
    <return>A struct of all itemdesc.cfg properties and values.</return> 
    <error>"Invalid parameter type"</error>
    <error>"Itemdesc.cfg entry for objtype X not found."</error>
    <relatedcfg>itemdesc.cfg</relatedcfg>
</function>

<function name="Realms">
    <prototype>Realms(realms:="")</prototype>
    <explain>Returns a dictionary of structs.</explain>
    <explain>If a single case-sensitive realm name is passed, will return the information for only that realm.</explain>
    <explain>example:
<code>    "realm_name" -> "width"
                    "height"
                    "mapid"
                    "toplevel_item_count"
                    "mobile_count"
                    "season"</code></explain>
    <return>A dictionary of structs of Realms.</return> 
</function>

  <function name="GetCmdLevelName">
    <prototype>GetCmdLevelName(number)</prototype>
    <parameter name="number" value="Integer" />
    <explain>Will get a command level's name.</explain>
    <return>CmdLevelName or Error</return>
	<error>"Invalid parameter type."</error>
	<relatedcfg>cmds.cfg</relatedcfg>
  </function>

  <function name="GetCmdLevelNumber">
    <prototype>GetCmdLevelNumber(name)</prototype>
    <parameter name="name" value="String" />
    <explain>Will get the numeric value of a command level.</explain>
    <return>CmdLevel or Error</return>
	<error>"Invalid parameter type."</error>
	<error>"Could not find a command level with that name."</error>
	<relatedcfg>cmds.cfg</relatedcfg>
  </function>

  <function name="IncRevision">
    <prototype>IncRevision( object )</prototype>
    <parameter name="object" value="UObject Ref" />
    <explain>Increases the internal "Revision" number of an UObject. Used to manually increase this number for scripted changes to things such as mob.race and such where core does not auto increase it.</explain>
    <return>1 on success</return>
    <error>"Invalid parameter type."</error>
  </function>

  <function name="ListenPoints">
    <prototype>ListenPoints( )</prototype>
    <explain>Array of listen points...</explain>
    <return>Array</return>
    <error>"Invalid parameter type."</error>
  </function>

  <function name="ListTextCommands">
    <prototype>ListTextCommands( )</prototype>
    <explain>Returns a dict of a dict of structs.</explain>
    <explain>Dict 1 - Package names Dict 2 - Command levels Struct - .dir .script</explain>
    <explain>
    <code>
	Example:
	foreach package in ( commands )
		Print("Pkg:"+_package_iter);
		foreach level in ( package )
			Print(" CmdLvl:"+_level_iter);
			foreach command in ( level )
				Print("     "+command);
				SleepMS(2);
			endforeach
			SleepMS(2);
		endforeach
		SleepMS(2);
	endforeach
    </code>
    </explain>
    <return>1 on success</return>
    <error>"Invalid parameter type."</error>
  </function>

  <function name="GetPackageByName">
    <prototype>GetPackageByName(name)</prototype>
    <parameter name="name" value="String" />
    <explain>Will return a package reference.</explain>
    <return>PackageRef or Error</return>
	<error>"Invalid parameter type."</error>
	<error>"No package found by that name."</error>
	<related>Package</related>
  </function>

  <function name="CreatePacket">
    <prototype>CreatePacket(type, size)</prototype>
    <parameter name="type" value="Integer" />
    <parameter name="size" value="Integer" />
    <explain>Creates a new packet object. Type is the byte command id that always is set as the first byte (no need to set it yourself). Size is the fixed-length size for this packet, or MSGLEN_VARIABLE if it is variable length (no need to figure out the size in advance, the packet buffer will be resized as need by using the Set* methods).</explain>
	<explain>Notes: polsys.em constants for this function:
<code>
const MSGLEN_VARIABLE := -1;</code></explain>
    <return>A new packet object or Error</return>
	<error>"Invalid parameter type."</error>
	<error>"Packet type too high"</error>
	<related>Packet</related>
  </function>
  
  <function name="AddRealm">
    <prototype>AddRealm(realm_name, base_realm)</prototype>
    <parameter name="realm_name" value="String - case-sensitive name of the realm" />
    <parameter name="base_realm" value="String - case-sensitive name of the realm" />
    <explain>Creates a new Realm based on an other realm, uses same map and regions.</explain>
    <return>1</return> 
    <error>"BaseRealm not found."</error>
    <error>"BaseRealm is a ShadowRealm."</error>
    <error>"Realmname already defined."</error>
  </function>
  
  <function name="DeleteRealm">
    <prototype>DeleteRealm(realm)</prototype>
    <parameter name="realm" value="String - case-sensitive name of the realm" />
    <explain>Deletes a ShadowRealm, only if the realm is "clean"</explain>
    <return>1</return> 
    <error>"Realm not found."</error>
    <error>"Realm is not a ShadowRealm."</error>
    <error>"Mobiles in Realm."</error>
    <error>"Items in Realm."</error>
  </function>
  
  <function name="MD5Encrypt">
    <prototype>MD5Encrypt(str)</prototype>
    <parameter name="str" value="String" />
    <explain>Encrypts given string.</explain>
    <return>MD5 hash string on success</return> 
    <error>"Invalid parameter"</error>
    <error>"String is empty"</error>
    <error>"Failed to encrypt"</error>
  </function>
        
</ESCRIPT>

=== polserver/polserver/docs/docs.polserver.com/pol100/boatem.xml
<?xml version='1.0' encoding="iso-8859-1"?>
<?xml-stylesheet type="text/xsl" href="escript.xslt" ?>
<!DOCTYPE ESCRIPT SYSTEM "escript.dtd">
<ESCRIPT>
  <fileheader fname="Boat.em">
    <filedesc>Functions for manipulating Multi Boat objects.</filedesc>
    <datemodified>08/31/2015</datemodified>
    <constant>const BOAT_SPEED_ONE_TILE 	:= 1;</constant>
    <constant>const BOAT_SPEED_SLOW		:= 2;</constant>
    <constant>const BOAT_SPEED_MEDIUM 	:= 3;</constant>
    <constant>const BOAT_SPEED_FAST 		:= 4;</constant>
  </fileheader>

  <function name="MoveBoat"> 
    <prototype>MoveBoat( boat, facing, speed := BOAT_SPEED_ONE_TILE )</prototype>
    <parameter name="boat" value="Boat Reference" />
    <parameter name="facing" value="Integer (0..7)" />
    <parameter name="speed" value="Integer (0..4)" />
    <explain>Moves a boat in the direction of an absolute facing</explain>
    <explain>0=N, 1=NE, 2=E, 3=SE, 4=S, 5=SW, 6=W, 7=NW</explain>
    <explain>speed to determine how fast the boat movement should be animated for smooth move</explain>
    <return>1 on success, 0 on failure</return>
    <error>none (returns 0 on invalid param)</error>
    <related>Boat</related>
  </function>

  <function name="MoveBoatXY"> 
    <prototype>MoveBoatXY( boat, x, y )</prototype>
    <parameter name="boat" value="Boat Reference" />
    <parameter name="x" value="Integer world coordinate" />
    <parameter name="y" value="Integer world coordinate" />
    <explain>Moves a boat to the specified world coordinates.</explain>
    <explain>Careful moving close to the world edge where a part of the boat might be out of bounds.</explain>
    <return>1 on success, 0 on failure</return>
    <error>Invalid Parameter</error>
    <related>Boat</related>
  </function>

  <function name="MoveBoatRelative"> 
    <prototype>MoveBoatRelative( boat, direction, speed := BOAT_SPEED_ONE_TILE )</prototype>
    <parameter name="boat" value="Boat Reference" />
    <parameter name="direction" value="Integer (0..7)" />
    <parameter name="speed" value="Integer (0..4)" />
    <explain>Move a boat in the direction of a relative facing. Same as MoveBoat, but adjusted for boat's facing.</explain>
    <explain>If boat faces East, 0 will move E, 1 will move SE, etc.</explain>
    <explain>speed to determine how fast the boat movement should be animated for smooth move</explain>
    <return>1 on success, 0 on failure</return>
    <error>none (returns 0 on invalid param)</error>
    <related>Boat</related>
  </function>

  <function name="RegisterItemWithBoat"> 
    <prototype>RegisterItemWithBoat( boat, item )</prototype>
    <parameter name="boat" value="Boat Reference" />
    <parameter name="item" value="Item Reference)" />
    <explain>'registering' an item with a boat causes the boat to move the item when it moves, if and only if the item is still on the boat.</explain>
    <return>1 always</return>
    <error>none (returns 0 on invalid param)</error>
    <related>Boat</related>
    <related>Item</related>
  </function>

  <function name="BoatFromItem"> 
    <prototype>BoatFromItem( item )</prototype>
    <parameter name="item" value="Item Ref" />
    <explain>if you have an itemref referring to a boat (typically in a doubleclick script) this will convert it into a boatref.</explain>
	<explain>Note that this should not be necessary anymore.</explain>
    <return>Boat Reference</return>
    <error>"Item wasn't a multi"</error>
    <error>"Multi wasn't a boat"</error>
    <error>"Invalid parameter type."</error>
    <related>Boat</related>
    <related>Item</related>
  </function>
  
  <function name="TurnBoat"> 
    <prototype>TurnBoat( boat, direction )</prototype>
    <parameter name="boat" value="Boat Reference" />
    <parameter name="direction" value="Integer (0..3)" />
    <explain>Turn a boat in a direction, relative to its current directon.</explain>
    <explain>direction is 0=none, 1=right, 2=flip, 3=left</explain>
    <return>true/false if the boat could be turned (i.e. wouldn't be in an invalid location after the turn)</return>
    <error>"Invalid Parameter type"</error>
    <related>Boat</related>
  </function>
  
  <function name="SystemFindBoatBySerial"> 
    <prototype>SystemFindBoatBySerial( serial )</prototype>
    <parameter name="serial" value="Integer" />
    <explain>given the serial number of a boat, return a boatref that can be used with MoveBoat, TurnBoat, etc.</explain>
    <explain>SystemFindObjectBySerial can find boats as well, should use that.</explain>
    <return>Boat Reference on success</return>
    <error>"Boat not found."</error>
    <related>Boat</related>
  </function>

</ESCRIPT>

=== polserver/polserver/docs/docs.polserver.com/pol100/storageem.xml
<?xml version='1.0' encoding="iso-8859-1"?>
<?xml-stylesheet type="text/xsl" href="escript.xslt" ?>
<!DOCTYPE ESCRIPT SYSTEM "escript.dtd">
<ESCRIPT>  
  <fileheader fname="Storage.em">
    <filedesc>Functions for working with internal storage areas.</filedesc>
    <datemodified>10/27/2007</datemodified>
  </fileheader>
  
  <function name="StorageAreas"> 
    <prototype>StorageAreas()</prototype>
    <explain>Returns a StorageAreas object, see object reference for details</explain>
    <return>StorageAreas object</return>
    <related>StorageAreas</related>
  </function>

<function name="FindStorageArea">
	<prototype>FindStorageArea( areaname )</prototype>
	<parameter name="areaname" value="String" />
	<explain>Gets a reference to the storage area named "areaname"</explain>
	<return>Storage Area reference on success</return>
	<error>none (returns 0 on invalid parameter or area not found)</error>
	<related>StorageArea</related>
</function>

<function name="FindRootItemInStorageArea">
	<prototype>FindRootItemInStorageArea( area, itemname )</prototype>
	<parameter name="area" value="Storage Area Reference" />
	<parameter name="itemname" value="String" />
	<explain>Finds the root item named "itemname" in the storage area named "area".</explain>
	<return>Item Reference on success</return>
	<error>"Invalid parameter type"</error>
	<error>"Root item not found."</error>
</function>

<function name="CreateStorageArea">
	<prototype>CreateStorageArea( areaname )</prototype>
	<parameter name="areaname" value="String" />
	<explain>Create a new storage area with name "areaname".</explain>
	<return>Storage Area reference on success</return>
	<error>Errors: none (returns 0 on invalid parameter)</error>
</function>

<function name="CreateRootItemInStorageArea">
	<prototype>CreateRootItemInStorageArea( area, itemname, objtype )</prototype>
	<parameter name="area" value="Storage Area Reference" />
	<parameter name="itemname" value="String" />
	<parameter name="objtype" value="Integer objtype, OR String ObjtypeName, OR GetItemDescriptor struct." />
	<explain>Creates the "root" (top-level) item in the storage area provided. "itemname" is the name of this
				item, and "objtype" is its type.</explain>
	<explain>Notes: The item is normally a container. For example, a bankbox is a storage area and the root item 
is the chest container. Normal items are then placed in this container.</explain>
    <return>Item Reference on success</return>
	<error>"Invalid parameter type"</error>
	<error>"Unable to create item"</error>
	<related>Item</related>
</function>

<function name="DestroyRootItemInStorageArea">
	<prototype>DestroyRootItemInStorageArea( area, itemname )</prototype>
	<parameter name="area" value="Storage Area Reference" />
	<parameter name="itemname" value="String" />
	<explain>Destroys the root item named "itemname" in storage area "area"</explain>
	<return>1 on delete success</return>
    <return>0 on item not found</return>
	<error>"Invalid parameter type"</error>
</function>

</ESCRIPT>

=== polserver/polserver/trunk/docs/docs.polserver.com/pol099/datafileem.xml
<?xml version='1.0' encoding="iso-8859-1"?>
<?xml-stylesheet type="text/xsl" href="escript.xslt" ?>
<!DOCTYPE ESCRIPT SYSTEM "escript.dtd">
<ESCRIPT>
  <fileheader fname="Datafile.em">
    <filedesc>Functions to access generic data files.</filedesc>
    <datemodified>10/27/2007</datemodified>
<constant>// OpenDataFile flags:</constant>
<constant>// can specify only one of the following:</constant>
<constant>const DF_KEYTYPE_STRING       := 0x00; // default</constant>
<constant>const DF_KEYTYPE_INTEGER      := 0x01;</constant>
  </fileheader>
    
  <function name="CreateDataFile"> 
    <prototype>CreateDataFile( filespec, flags := DF_KEYTYPE_STRING )</prototype>
    <parameter name="filespec" value="String" />
    <parameter name="flags" value="Integer" />
    <explain>Creates a new data file.</explain>
    <explain>filespec is in normal package descriptor format. 'filename' or '::filename' will create the new data file /data/ds/filename. ':pkgname:filename' will create /data/ds/pkgname/filename.</explain>
    <explain>flags specifies if the keys of the new datafile are strings OR integers.</explain>
    <return>DataFile Reference. See the DataFile object documentation.</return>
    <error>"Error in descriptor"</error>
    <error>"An exception occurred"</error>
    <error>"Invalid parameter type"</error>
    <related>Datafile</related>
  </function>

  <function name="OpenDataFile"> 
    <prototype>OpenDataFile( filespec )</prototype>
    <parameter name="filespec" value="String" />
    <explain>Opens a datafile for access.</explain>
    <explain>filespec is in normal package descriptor format. 'filename' or '::filename' will open the data file /data/ds/filename. ':pkgname:filename' will open /data/ds/pkgname/filename.</explain>
    <return>DataFile Reference. See the DataFile object documentation.</return>
    <error>"Datafile does not exist"</error>
    <error>"Error in descriptor"</error>
    <error>"An exception occurred"</error>
    <error>"Invalid parameter type"</error>
    <related>Datafile</related>
  </function>
  
  <function name="UnloadDataFile"> 
    <prototype>UnloadDataFile( filespec )</prototype>
    <parameter name="filespec" value="String" />
    <explain>Unloads a datafile</explain>
    <explain>filespec is in normal package descriptor format. 'filename' or '::filename' will unload the data file /data/ds/filename. ':pkgname:filename' will unload /data/ds/pkgname/filename.</explain>
    <return>1 on success</return>
    <error>"Unable to find data store file"</error>
    <error>"Invalid parameter type"</error>
    <related>Datafile</related>
  </function>
  
  <function name="ListDataFiles"> 
    <prototype>ListDataFiles( )</prototype>
    <explain>Returns an array of structs containing: </explain>
    <explain>.pkg - name of the package the datafile belongs to</explain>
    <explain>.name - name of the file</explain>
    <explain>.descriptor - :pkg:name</explain>
    <return>Array of Structs</return>
    <related>Datafile</related>
  </function>
  
</ESCRIPT>
