=== polserver/polserver/docs/docs.polserver.com/pol100/escript.dtd
<!ELEMENT ESCRIPT (fileheader,function*)>
<!ELEMENT fileheader (filedesc, datemodified,constant*)>
  <!ATTLIST fileheader fname CDATA #REQUIRED>
  <!ELEMENT filedesc (#PCDATA)>
  <!ELEMENT datemodified (#PCDATA)>
  <!ELEMENT constant (#PCDATA)> 
  
<!ELEMENT function (prototype, parameter*, explain*, return*, error*, related*, relatedcfg*)>
  <!ATTLIST function name CDATA #REQUIRED>
  <!ELEMENT prototype (#PCDATA)>
  <!ELEMENT parameter EMPTY>
    <!ATTLIST parameter name CDATA #REQUIRED>
    <!ATTLIST parameter value CDATA #REQUIRED>
  <!ELEMENT explain (#PCDATA | code)*>
    <!ELEMENT code (#PCDATA)>
  <!ELEMENT return (#PCDATA)>
  <!ELEMENT error (#PCDATA)>
  <!ELEMENT related (#PCDATA)>
  <!ELEMENT relatedcfg (#PCDATA)>

=== polserver/polserver/tags/R2013-09-03_099/docs/docs.polserver.com/pol099/vitalsem.xml
<?xml version='1.0' encoding="iso-8859-1"?>
<?xml-stylesheet type="text/xsl" href="escript.xslt" ?>
<!DOCTYPE ESCRIPT SYSTEM "escript.dtd">
<ESCRIPT>  
  <fileheader fname="Vitals.em">
    <filedesc>Functions for working with mobile vitals.</filedesc>
    <datemodified>02/25/2010</datemodified>
<constant>//Apply*Damage constants</constant>
<constant>const DAMAGE_USE_REPSYS  := 1;</constant>
<constant>const DAMAGE_NO_REPSYS   := 0;</constant>
<constant>const DAMAGE_NO_SHOW     := 0;</constant>
<constant>const DAMAGE_SHOW        := 1;</constant>
<constant>const DAMAGE_USE_DEFAULT := 2;</constant>
<constant>//RecalcVital constants</constant>
<constant>const RECALC_INTRINSIC_MOD    := 1;</constant>
<constant>const RECALC_NO_INTRINSIC_MOD := 0;</constant>
<constant>const RECALC_VITALS           := 1;</constant>
<constant>const RECALC_NO_VITALS        := 0;</constant>
  </fileheader>
  
<function name="ApplyDamage">
    <prototype>ApplyDamage( Character, Hits, userepsys := DAMAGE_USE_REPSYS, send_damage := DAMAGE_USE_DEFAULT )</prototype>
	<parameter name="Character" value="Character Reference" />
	<parameter name="Hits" value="Real (0.0 to 30000.0)" />
	<parameter name="userepsys" value="Integer (optional, default DAMAGE_USE_REPSYS)" />
	<parameter name="send_damage" value="Integer (optional, default DAMAGE_USE_DEFAULT)" />
	<explain>Decreases a character's hit points, after reducing damage due to armor.</explain>
	<explain>Notes: vitals.em constants for userepsys:
<code>
const DAMAGE_USE_REPSYS  := 1;
const DAMAGE_NO_REPSYS   := 0;
const DAMAGE_NO_SHOW     := 0;
const DAMAGE_SHOW        := 1;
const DAMAGE_USE_DEFAULT := 2;</code></explain>
  <explain>DAMAGE_USE_DEFAULT uses the SendDamagePacket setting from combat.cfg</explain>
 	<explain>(Old notes:) The steps taken are as follows:
			A piece of armor is chosen randomly, based on probabilities in ARMRZONE.CFG. 
			Damage is reduced by 50% to 100% of the armor's AR. 
			Remaining damage is halved. 
			"I'm Hit" animation is played. 
			Damage is applied. 
			Mobile is killed if hit points are now zero. 
		   Invokes Reputation system effects.</explain>
	<return>Real damage applied to mobile on success</return>
	<error>"Invalid parameter type"</error>
	<error>"Damage is out of range"</error>
	<related>Character</related>
</function>

<function name="ApplyRawDamage">
    <prototype>ApplyRawDamage( Character, Hits, userepsys := DAMAGE_USE_REPSYS, send_damage := DAMAGE_USE_DEFAULT )</prototype>
	<parameter name="Character" value="Character Reference" />
	<parameter name="Hits" value="Integer (0..255)" />
	<parameter name="userepsys" value="Integer (optional, default DAMAGE_USE_REPSYS)" />
	<parameter name="send_damage" value="Integer (optional, default DAMAGE_USE_DEFAULT)" />
	<explain>Decreases a character's hit points.  If this causes hit points to drop to zero, kills the character.</explain>
 	<explain>Notes: Armor is ignored.</explain>
  <explain>Invokes Reputation system effects.</explain>
  <explain>Notes: vitals.em constants for userepsys:
<code>
const DAMAGE_USE_REPSYS  := 1;
const DAMAGE_NO_REPSYS   := 0;
const DAMAGE_NO_SHOW     := 0;
const DAMAGE_SHOW        := 1;
const DAMAGE_USE_DEFAULT := 2;</code></explain>
  <explain>DAMAGE_USE_DEFAULT uses the SendDamagePacket setting from combat.cfg</explain>
  <return>1 on success</return>
	<error>none (returns 0 on invalid parameter)</error>
  <related>Character</related>
</function>

<function name="HealDamage">
    <prototype>HealDamage( Character, Hits )</prototype>
	<parameter name="Character" value="Character Reference" />
	<parameter name="Hits" value="Integer (0..255)" />
	<explain>Increases a character's hit points, up to the character's maximum.</explain>
	<explain>Notes: Invokes Reputation system effects.</explain>
	<return>1 if some part of the damage could be healed.</return>
	<error>"Invalid parameter"</error>
	<related>Character</related>
</function>

<function name="ConsumeMana">
	<prototype>ConsumeMana( who, spellid )</prototype>
	<parameter name="who" value="Character Reference" />
	<parameter name="spellid" value="Integer" />
	<explain>Consumes amount of "Mana" for "who" for the spell as defined in spells.cfg</explain>
	<explain>Notes: spells.cfg files define spells and spell ids.</explain>
	<explain>Consumes from "Mana" vital.</explain>
	<return>1 on success</return>
	<error>"Invalid parameter"</error>
	<error>"No such spell"</error>
	<error>"Spell ID out of range"</error>
	<related>Character</related>
	<relatedcfg>spells.cfg</relatedcfg>
</function>

<function name="ConsumeVital">
	<prototype>ConsumeVital( who, vital, hundredths )</prototype>
	<parameter name="who" value="Character Reference" />
	<parameter name="vital" value="String (vital name)" />
	<parameter name="hundreths" value="Integer" />
	<explain>Consumes an amount of vital "vital" in hundreths. for example, ConsumeVital(who, "Stamina", 100) 
consumes one point of stamina.</explain>
	<return>1 on consume success or 0 on failure (insufficient value for the vital)</return>
	<error>"Invalid parameter type" including if vital was not found as a vital name</error>
	<related>Character</related>
	<relatedcfg>vitals.cfg</relatedcfg>
</function>

<function name="GetVital">
	<prototype>GetVital( character, vitalname )</prototype>
	<parameter name="character" value="Character Reference" />
	<parameter name="vitalname" value="String (vital name)" />
	<explain>Gets the current value of "vitalname" on "character".</explain>
	<return>Integer current value of the vital on success or Error</return>
	<error>"Invalid parameter type" including if vitalname was not found as a vital</error>
	<related>Character</related>
	<relatedcfg>vitals.cfg</relatedcfg>
</function>

<function name="GetVitalName">
	<prototype>GetVitalName( alias_name )</prototype>
	<parameter name="alias_name" value="String" />
	<explain>Returns the real vital name from an alias</explain>
	<return>String</return>
	<error>"Invalid parameter type"</error>
	<related>Character</related>
	<relatedcfg>vitals.cfg</relatedcfg>
</function>

<function name="GetVitalMaximumValue">
	<prototype>GetVitalMaximumValue( character, vitalname )</prototype>
	<parameter name="character" value="Character Reference" />
	<parameter name="vitalname" value="String (vital name)" />
	<explain>Gets the maximum value of "vitalname" on "character" </explain>
  	<return>Integer maximum value of the vital on success or Error</return>
	<error>"Invalid parameter type" including if vitalname was not found as a vital</error>
  	<related>Character</related>
  	<relatedcfg>vitals.cfg</relatedcfg>
</function>

<function name="GetVitalRegenRate">	
	<prototype>GetVitalRegenRate( character, vitalname )</prototype>
	<parameter name="character" value="Character Reference" />
	<parameter name="vitalname" value="String (vital name)" />
	<explain>Returns the regeneration rate for "vitalname" on "character"</explain>
	<return>Integer regeneration rate of the vital on success</return>
	<error>"Invalid parameter type" including if vitalname was not found as a vital</error>
	<related>Character</related>
	<related>String</related>
	<relatedcfg>vitals.cfg</relatedcfg>
</function>
	
<function name="RecalcVitals">
	<prototype>RecalcVitals( character, calc_attribute := RECALC_INTRINSIC_MOD, calc_vital := RECALC_VITALS )</prototype>
	<parameter name="character" value="Character Reference" />
	<parameter name="calc_attribute" value="Integer/String (attribute name)" />
	<parameter name="calc_vital" value="Integer/String (vital name)" />
	<explain>if default values are passed recalculates regen rates and maximum values from the exported functions in vitals.cfg for all vitals on a mobile
	  and the intrinsic modifier from the exported functions in attributes.cfg for all attributes</explain>
	<explain>if calc_attribute is set to RECALC_NO_INTRINSIC_MOD it skips the recalculation of attributes</explain>
	<explain>if calc_attribute is set to an attribute name it only calculates for given attribute</explain>
	<explain>if calc_vital is set to RECALC_NO_VITALS it skips the recalculation of vitals</explain>
	<explain>if calc_vital is set to an vital name it only calculates for given vital</explain>
	<explain>Notes: vitals.em constants:
<code>
const RECALC_INTRINSIC_MOD    := 1;
const RECALC_NO_INTRINSIC_MOD := 0;
const RECALC_VITALS           := 1;
const RECALC_NO_VITALS        := 0;</code></explain>
	<return>1 on success</return>
	<error>"Mobile must be online."</error>
	<error>"Invalid parameter type"</error>
	<error>"Vital not defined: {given name}"</error>
	<error>"Attribute not defined: {given name}"</error>
	<related>Character</related>
	<relatedcfg>vitals.cfg</relatedcfg>
	<relatedcfg>attributes.cfg</relatedcfg>
</function>
	
<function name="SetVital">
	<prototype>SetVital( character, vitalname, value )</prototype>
	<parameter name="character" value="Character Reference" />
	<parameter name="vitalname" value="String (vital name)" />
	<parameter name="value" value="Integer (in hundreths)" />
	<explain>Sets the current value for "vitalname" on "character" in hundreths.</explain>
	<return>1 on success</return>
	<error>"Invalid parameter type" including if vitalname was not found as a vital</error>
	<related>Character</related>
	<relatedcfg>vitals.cfg</relatedcfg>
</function>

</ESCRIPT>

=== polserver/polserver/docs/docs.polserver.com/pol100/utilem.xml
<?xml version='1.0' encoding="iso-8859-1"?>
<?xml-stylesheet type="text/xsl" href="escript.xslt" ?>
<!DOCTYPE ESCRIPT SYSTEM "escript.dtd">
<ESCRIPT>
  <fileheader fname="Util.em">
    <filedesc>Utility functions</filedesc>
    <datemodified>08/16/2020</datemodified>
    <constant>const UUID_NIL := "00000000-0000-0000-0000-000000000000";</constant>
    <constant>const UUID_MAX := "ffffffff-ffff-ffff-ffff-ffffffffffff";</constant>
  </fileheader>

  <function name="RandomInt">
    <prototype>RandomInt(below_this_number)</prototype>
    <parameter name="below_this_number" value="Integer" />
    <explain>Returns a random integer below the passed parameter and greater or equal to zero.</explain>
    <return>Integer R such that 0 less or equal to R less than below_this_number</return>
	<error>"RandomInt() expects a positive integer"</error>
  </function>

  <function name="RandomIntMinMax">
    <prototype>RandomIntMinMax(minValue, maxValue)</prototype>
    <parameter name="minValue" value="Integer" />
    <parameter name="maxValue" value="Integer" />
    <explain>Returns a random integer between the Min and Max integers passed. Accepts negative Integers and if parameters in wrong order swaps them.</explain>
    <return>Integer Randomly between Min and Max parameters</return>
	<error>"RandomIntMinMax() expects an integer"</error>
  </function>

  <function name="RandomFloat">
    <prototype>RandomFloat(below_this_float)</prototype>
    <parameter name="below_this_float" value="Real" />
    <explain>Returns a random real below the passed parameter and greater or equal to zero.</explain>
    <return>Real R such that 0 less or equal to R less than below_this_number</return>
	<error>"RandomFloat() expects a Real parameter"</error>
  </function>

  <function name="RandomDiceRoll">
    <prototype>RandomDiceRoll(dice_string, allow_negatives := 0)</prototype>
    <parameter name="dice_string" value="String" />
    <parameter name="allow_negatives" value="Integer"/>
    <explain>Returns a random number according to the passed die roll string. This is standard NdS+X format. N=number of dies to roll, S=number of sides per die, X=integer to add(or subtract) after roll.</explain>
    <explain>If <code>allow_negatives</code> is <code>1</code>, a negative dice roll will be returned as-is, and will not be capped at <code>0</code>.</explain>
    <explain>Here's some acceptable examples:
<code>
4
d4
d6+6
d6-2
2d12
2d8+12
2d8-4
</code></explain>
    <return>Valkyrie's pedantic wording: "returns an integer greater or equal to N+X and not more than N*S+X"</return>
  </function>

  <function name="RandomUUID">
    <prototype>RandomUUID( version := 4 )</prototype>
    <explain>Returns a UUID according to RFC 9562. Supported versions are 4 (random) and 7 (timestamp + random)</explain>
    <return>String</return>
    <error>"Invalid parameter type"</error>
    <error>"Invalid version"</error>
  </function>

  <function name="StrFormatTime">
    <prototype>StrFormatTime( format_string, time_stamp:=0 )</prototype>
    <parameter name="format_string" value="String" />
    <parameter name="time_stamp" value="Integer" />
    <explain>Takes in the StrFTime() specifiers for the format string.</explain>
    <explain>If time_stamp is 0, it will use POLCore().systime.</explain>
    <explain>For format_string information, please go to http://www.cppreference.com/stddate/strftime.html</explain>
    <return>String</return>
    <error>"No time string passed."</error>
  </function>

</ESCRIPT>

=== polserver/polserver/docs/docs.polserver.com/pol099/mathem.xml
<?xml version='1.0' encoding="iso-8859-1"?>
<?xml-stylesheet type="text/xsl" href="escript.xslt" ?>
<!DOCTYPE ESCRIPT SYSTEM "escript.dtd">
<ESCRIPT>
  <fileheader fname="Math.em">
    <filedesc>Mathematic functions for your enjoyment</filedesc>
    <datemodified>08/31/2015</datemodified>
  </fileheader>

  <function name="Sin"> 
    <prototype>Sin(x)</prototype>
    <parameter name="x" value="Real, in radians" />
    <explain>Computes the sine of x</explain>
    <return>Real number</return>
    <error>"Invalid parameter type"</error>
  </function>

  <function name="Cos"> 
    <prototype>Cos(x)</prototype>
    <parameter name="x" value="Real, in radians" />
    <explain>Computes the cosine of x</explain>
    <return>Real number</return>
    <error>"Invalid parameter type"</error>
  </function>

  <function name="Tan"> 
    <prototype>Tan(x)</prototype>
    <parameter name="x" value="Real, in radians" />
    <explain>Computes the tangent of x</explain>
    <return>Real number</return>
    <error>"Invalid parameter type"</error>
  </function>

  <function name="ASin"> 
    <prototype>ASin(x)</prototype>
    <parameter name="x" value="Real, in radians" />
    <explain>Computes the arcsine of x</explain>
    <return>Real number in radians</return>
    <error>"Invalid parameter type"</error>
  </function>

  <function name="ACos"> 
    <prototype>ACos(x)</prototype>
    <parameter name="x" value="Real, in radians" />
    <explain>Computes the arccosine of x</explain>
    <return>Real number in radians</return>
    <error>"Invalid parameter type"</error>
  </function>

  <function name="ATan"> 
    <prototype>ATan(x)</prototype>
    <parameter name="x" value="Real, in radians" />
    <explain>Computes the arctangent of x</explain>
    <return>Real number in radians</return>
    <error>"Invalid parameter type"</error>
  </function>

  <function name="RadToDeg"> 
    <prototype>RadToDeg( radians )</prototype>
    <parameter name="radians" value="Real, in radians" />
    <explain>Converts the radian parameter to degrees</explain>
    <return>Real number in degrees</return>
    <error>"Invalid parameter type"</error>
  </function>    

  <function name="DegToRad"> 
    <prototype>DegToRad( degrees )</prototype>
    <parameter name="degrees" value="Real, in degrees" />
    <explain>Converts the degrees parameter to radians</explain>
    <return>Real number in radians</return>
    <error>"Invalid parameter type"</error>
  </function>

  <function name="Pow"> 
    <prototype>Pow(x,y)</prototype>
    <parameter name="x" value="Real" />
    <parameter name="y" value="Real" />
    <explain>Computes x ^ y</explain>
    <return>Real number</return>
    <error>"Invalid parameter type"</error>
  </function>

  <function name="Sqrt"> 
    <prototype>Sqrt(x)</prototype>
    <parameter name="x" value="Real" />
    <explain>Computes the square root of x</explain>
    <return>Real number</return>
    <error>"Invalid parameter type"</error>
  </function>

  <function name="Root"> 
    <prototype>Root(x,y)</prototype>
    <parameter name="x" value="Real" />
    <parameter name="y" value="Real" />
    <explain>Computes the y root of x (same as Pow(x,1.0/y)).</explain>
    <return>Real number</return>
    <error>"Invalid parameter type"</error>
  </function>

  <function name="Abs"> 
    <prototype>Abs(x)</prototype>
    <parameter name="x" value="Real or Integer" />
    <explain>Computes the absolute value of x</explain>
    <return>Real number</return>
    <error>"Invalid parameter type"</error>
  </function>

  <function name="Log10"> 
    <prototype>Log10(x)</prototype>
    <parameter name="x" value="Real" />
    <explain>Computes log(base 10) of x</explain>
    <return>Real number</return>
    <error>"Invalid parameter type"</error>
  </function>

  <function name="LogE"> 
    <prototype>LogE(x)</prototype>
    <parameter name="x" value="Real" />
    <explain>Computes the natural log of x</explain>
    <return>Real number</return>
    <error>"Invalid parameter type"</error>
  </function>

   <function name="Ceil"> 
    <prototype>Ceil(x)</prototype>
    <parameter name="x" value="Real" />
    <explain>Computes the ceiling of x</explain>
    <return>Real that is smallest integer >= x</return>
    <error>"Invalid parameter type"</error>
  </function>

  <function name="Floor"> 
    <prototype>Floor(x)</prototype>
    <parameter name="x" value="Real" />
    <explain>Computes the floor of x</explain>
    <return>Real that is largest integer &lt;= x</return>
    <error>"Invalid parameter type"</error>
  </function>

  <function name="ConstPi"> 
    <prototype>ConstPi()</prototype>
    <explain>Returns an approximation of the trancendental number Pi</explain>
    <explain>
    Pi is a numerical constant that represents the ratio of a circle's circumference to 
    its diameter on a flat plane surface. The value is the same regardless of the size of 
    the circle. The decimal expansion of pi is a nonterminating, nonrepeating sequence of 
    digits. Pi can be expressed through the Fourier series pi = 4 - (4/3) + (4/5) - (4/7) + (4/9) - ... </explain>
    <return>Real number (3.14159....)</return>
  </function>

  <function name="ConstE"> 
    <prototype>ConstE()</prototype>
    <explain>Returns an approximation of the trancendental number E</explain>
    <explain>
    e, is an irrational NUMBER occurring widely in mathematics and science, approximately 
    equal to the value 2.71828; it is the base of natural, or Naperian, LOGARITHMS. Like pi, 
    e is transcendental, i.e., not a ROOT of any algebraic equation. It is defined as the 
    LIMIT of the expression (1 + 1/n)^n as n becomes infinitely large. Expressions of the 
    form e^(x), known as the exponential function, occur in applications ranging from 
    statistics to nuclear physics</explain>
    <return>Real number</return>
  </function> 

  <function name="FormatRealToString"> 
    <prototype>FormatRealToString( value, precision )</prototype>
    <parameter name="value" value="Real" />
    <parameter name="precision" value="Integer" />
    <explain>Who knows if this even works at all</explain>
    <return>String rep of the real number</return>
    <error>"Invalid parameter type"</error>
  </function>

  <function name="Min"> 
    <prototype>Min( x, y:=0 )</prototype>
    <parameter name="x" value="Integer/Double/Array" />
    <parameter name="y" value="Integer/Double" />
    <explain>The numerically lowest Integer of the parameter values. Will return int/dbl based on parameter types passed.</explain>
    <explain>If first param is an Array second will be ignored and returns lowest int/dbl entry.</explain>
    <return>Integer/Double</return>
    <error>"Invalid parameter type"</error>
    <error>"Array empty"</error>
    <error>"No Integer/Double elements"</error>
  </function>

  <function name="Max"> 
    <prototype>Max( x, y:=0)</prototype>
    <parameter name="x" value="Integer/Double/Array" />
    <parameter name="y" value="Integer/Double" />
    <explain>The numerically highest Integer of the parameter values. Will return int/dbl based on parameter types passed.</explain>
    <explain>If first param is an Array second will be ignored and returns lowest int/dbl entry.</explain>
    <return>Integer/Double</return>
    <error>"Invalid parameter type"</error>
    <error>"Array empty"</error>
    <error>"No Integer/Double elements"</error>
  </function>
    
</ESCRIPT>

=== polserver/polserver/docs/docs.polserver.com/pol100/httpem.xml
<?xml version='1.0' encoding="iso-8859-1"?>
<?xml-stylesheet type="text/xsl" href="escript.xslt" ?>
<!DOCTYPE ESCRIPT SYSTEM "escript.dtd">
<ESCRIPT>
  <fileheader fname="HTTP.em">
    <filedesc>Functions to send and receive data over an HTTP connection using POL's internal webserver. Scripts in /scripts/www are considered at the top level directory. I.e. http://192.168.0.5:8088/online.ecl </filedesc>
    <filedesc>Scripts stored in packages can be retrieved by accessing /pkg/packagename/script.ecl I.e. http://127.0.0.1:8088/pkg/guild/guilds.ecl </filedesc>
    <datemodified>02/06/2023</datemodified>
  </fileheader>
    
  <function name="WriteStatus"> 
    <prototype>WriteStatus( code, reason := "" )</prototype>
    <parameter name="code" value="Integer" />
    <parameter name="reason" value="String" />
    <explain>Writes the status code provided. If no reason provided, one will be calculated from the code (if possible). This can only used once before WriteHeader(), WriteHtml(), and WriteHtmlRaw().</explain>
    <return>1 on success</return>
    <error>"Socket is disconnected"</error>
    <error>"Cannot send status after WriteStatus, WriteHeader, WriteHtml, or WriteHtmlRaw"</error>
    <error>"Invalid parameter type"</error>
  </function>

  <function name="WriteHeader"> 
    <prototype>WriteHeader( name, value )</prototype>
    <parameter name="name" value="String" />
    <parameter name="value" value="String" />
    <explain>Writes the header provided. This function can be used to change the response's Content-Type from the default "text/html". This can only used before WriteHtml() and WriteHtmlRaw().</explain>
    <return>1 on success</return>
    <error>"Socket is disconnected"</error>
    <error>"Cannot send headers after WriteHtml or WriteHtmlRaw"</error>
    <error>"Invalid parameter type"</error>
  </function>

  <function name="WriteHtml"> 
    <prototype>WriteHtml( html )</prototype>
    <parameter name="html" value="String" />
    <explain>Writes a line of HTML to the "virtual webpage" that will be sent to the connecting browser and appends a new-line.</explain>
    <return>1 always</return>
    <error>"Socket is disconnected"</error>
    <error>"Invalid parameter type"</error>
  </function>

  <function name="WriteHtmlRaw"> 
    <prototype>WriteHtmlRaw( html )</prototype>
    <parameter name="html" value="String" />
    <explain>Writes a line of HTML to the "virtual webpage" that will be sent to the connecting browser, does NOT append a new-line.</explain>
    <return>1 always</return>
    <error>"Socket is disconnected"</error>
    <error>"Invalid parameter type"</error>
  </function>

  <function name="QueryParam"> 
    <prototype>QueryParam( param )</prototype>
    <parameter name="param" value="String" />
    <explain>Query's the accessed URL for any embedded parameters. (see your favorite HTML docs for parameter embedding! :) )</explain>
    <explain>Example: http://pol.server.com:8080/querytest.ecl?par=wibble&amp;name=
<code>
QueryParam( "par" ) ---> "wibble"
QueryParam( "name" ) --> ""
QueryParam( "heat" ) --> 0 [integer]
</code></explain>
    <return>String value of the embedded param, or 0 if not found.</return>
    <error>"Invalid parameter type"</error>
  </function>

  <function name="QueryIP"> 
    <prototype>QueryIP()</prototype>
    <explain>returns the IP address of the connecting browser</explain>
    <return>String IP address, i.e. "192.168.0.5"</return>
  </function>

  
</ESCRIPT>
