=== polserver/polserver/docs/docs.polserver.com/pol100/escript.dtd
<!ELEMENT ESCRIPT (fileheader,function*)>
<!ELEMENT fileheader (filedesc, datemodified,constant*)>
  <!ATTLIST fileheader fname CDATA #REQUIRED>
  <!ELEMENT filedesc (#PCDATA)>
  <!ELEMENT datemodified (#PCDATA)>
  <!ELEMENT constant (#PCDATA)> 
  
<!ELEMENT function (prototype, parameter*, explain*, return*, error*, related*, relatedcfg*)>
  <!ATTLIST function name CDATA #REQUIRED>
  <!ELEMENT prototype (#PCDATA)>
  <!ELEMENT parameter EMPTY>
    <!ATTLIST parameter name CDATA #REQUIRED>
    <!ATTLIST parameter value CDATA #REQUIRED>
  <!ELEMENT explain (#PCDATA | code)*>
    <!ELEMENT code (#PCDATA)>
  <!ELEMENT return (#PCDATA)>
  <!ELEMENT error (#PCDATA)>
  <!ELEMENT related (#PCDATA)>
  <!ELEMENT relatedcfg (#PCDATA)>

=== polserver/polserver/trunk/docs/docs.polserver.com/pol099/clilocem.xml
<?xml version='1.0' encoding="iso-8859-1"?>
<?xml-stylesheet type="text/xsl" href="escript.xslt" ?>
<!DOCTYPE ESCRIPT SYSTEM "escript.dtd">
<ESCRIPT>  
  <fileheader fname="Cliloc.em">
    <filedesc>Functions for sending Cliloc (Client Localized) messages to the Client.</filedesc>
    <datemodified>10/27/2007</datemodified>
    <constant>const _DEFAULT_CLFONT  := 3;</constant>
    <constant>const _DEFAULT_CLCOLOR := 0x3B2;</constant>
  </fileheader>
  
  <function name="SendSysMessageCL"> 
    <prototype>SendSysMessageCL(character, cliloc_num, uc_text:={}, font:=_DEFAULT_CLFONT, color:=_DEFAULT_CLCOLOR)</prototype>
    <parameter name="character" value="Character reference to receive the text" />
    <parameter name="cliloc_num" value="Cliloc Number you wish to be displayed." />
    <parameter name="uc_text" value="Array of 2-byte integers, where each integer is a Unicode character. Only used when the cliloc accepts arguments for replacement." />
    <parameter name="font" value="Integer (optional) font code. Not the same as non-unicode font codes" />
    <parameter name="color" value="Integer (optional) color code. Not the same color as the same value for non-unicode prints" />
    <explain>Displays a Cliloc (Client Localized) system message to 'character'. Arguments for the cliloc itself are seperated with a tab (\t) character.</explain>
    <explain>uc_text MUST be an array of integers representing unicode characters.</explain>
    <explain>Integers must be "Big Endian" (0x1234) and not "Little Endian" (0x3412).</explain>
    <explain>Integers will be clipped internally to 2-bytes (value masked with 0xFFFF)</explain>
    <explain>The Array must be terminated with zero. (0x0000)</explain>
    <explain>
    <code>
Argument example: 
Cliloc Number: 1042762: 
Cliloc ENU String: "Only ~1_AMOUNT~ gold could be deposited. A check for ~2_CHECK_AMOUNT~ gold was returned to you."
The uc_text string may have "100 thousand\t25 hundred", which in turn would modify the string:
"Only 100 thousand gold could be deposited. A check for 25 hundred gold was returned to you."
</code>
    </explain>
    <return>1 on success</return>
    <error>"Unicode array exceeds maximum size." (200 characters)</error>
    <error>"Invalid value in Unicode array."</error>
    <error>"A parameter was invalid"</error>
    <related>Array</related>
  </function>

  <function name="PrintTextAboveCL"> 
    <prototype>PrintTextAboveCL(character, cliloc_num, uc_text:={}, font:=_DEFAULT_CLFONT, color:=_DEFAULT_CLCOLOR)</prototype>
    <parameter name="character" value="Character reference to receive the text" />
    <parameter name="cliloc_num" value="Cliloc Number you wish to be displayed." />
    <parameter name="uc_text" value="Array of 2-byte integers, where each integer is a Unicode character. Only used when the cliloc accepts arguments for replacement." />
    <parameter name="font" value="Integer (optional) font code. Not the same as non-unicode font codes" />
    <parameter name="color" value="Integer (optional) color code. Not the same color as the same value for non-unicode prints" />
    <explain>Displays a Cliloc (Client Localized) message above 'character'. Arguments for the cliloc itself are seperated with a tab (\t) character.</explain>
    <explain>uc_text MUST be an array of integers representing unicode characters.</explain>
    <explain>Integers must be "Big Endian" (0x1234) and not "Little Endian" (0x3412).</explain>
    <explain>Integers will be clipped internally to 2-bytes (value masked with 0xFFFF)</explain>
    <explain>The Array must be terminated with zero. (0x0000)</explain>
    <explain>
    <code>
Argument example: 
Cliloc Number: 1042762: 
Cliloc ENU String: "Only ~1_AMOUNT~ gold could be deposited. A check for ~2_CHECK_AMOUNT~ gold was returned to you."
The uc_text string may have "100 thousand\t25 hundred", which in turn would modify the string:
"Only 100 thousand gold could be deposited. A check for 25 hundred gold was returned to you."
    </code>
    </explain>
    <return>1 on success</return>
    <error>"Unicode array exceeds maximum size." (200 characters)</error>
    <error>"Invalid value in Unicode array."</error>
    <error>"A parameter was invalid"</error>
    <related>Array</related>
  </function>

  <function name="PrintTextAbovePrivateCL"> 
    <prototype>PrintTextAbovePrivateCL(character, object, cliloc_num, uc_text:={}, font:=_DEFAULT_CLFONT, color:=_DEFAULT_CLCOLOR)</prototype>
    <parameter name="character" value="Character reference to receive the text" />
    <parameter name="object" value="UObject reference to print the text above" />
    <parameter name="cliloc_num" value="Cliloc Number you wish to be displayed." />
    <parameter name="uc_text" value="Array of 2-byte integers, where each integer is a Unicode character. Only used when the cliloc accepts arguments for replacement." />
    <parameter name="font" value="Integer (optional) font code. Not the same as non-unicode font codes" />
    <parameter name="color" value="Integer (optional) color code. Not the same color as the same value for non-unicode prints" />
    <explain>Displays a Cliloc (Client Localized) message above 'character'. Arguments for the cliloc itself are seperated with a tab (\t) character.</explain>
    <explain>uc_text MUST be an array of integers representing unicode characters.</explain>
    <explain>Integers must be "Big Endian" (0x1234) and not "Little Endian" (0x3412).</explain>
    <explain>Integers will be clipped internally to 2-bytes (value masked with 0xFFFF)</explain>
    <explain>The Array must be terminated with zero. (0x0000)</explain>
    <explain>
    <code>
Argument example: 
Cliloc Number: 1042762: 
Cliloc ENU String: "Only ~1_AMOUNT~ gold could be deposited. A check for ~2_CHECK_AMOUNT~ gold was returned to you."
The uc_text string may have "100 thousand\t25 hundred", which in turn would modify the string:
"Only 100 thousand gold could be deposited. A check for 25 hundred gold was returned to you."
    </code>
    </explain>
    <return>1 on success</return>
    <error>"Unicode array exceeds maximum size." (200 characters)</error>
    <error>"Invalid value in Unicode array."</error>
    <error>"A parameter was invalid"</error>
    <related>Array</related>
  </function>
  
</ESCRIPT>

=== polserver/polserver/docs/docs.polserver.com/pol099/partyem.xml
<?xml version='1.0' encoding="iso-8859-1"?>
<?xml-stylesheet type="text/xsl" href="escript.xslt" ?>
<!DOCTYPE ESCRIPT SYSTEM "escript.dtd">
<ESCRIPT>  
  <fileheader fname="Party.em">
    <filedesc>Functions for working with parties in eScript.</filedesc>
    <datemodified>08/31/2015</datemodified>
  </fileheader>

<function name="CreateParty">
	<prototype>CreateParty( leader, firstmember)</prototype>
	<parameter name="leader" value="Character Reference" />
	<parameter name="firstmember" value="Character Reference" />
	<explain>Creates a Party with given leader and firstmember.</explain>
	<return>1 on success</return>
	<error>"Leader is already in a party"</error>
	<error>"Leader is already candidate of a party"</error>
	<error>"Leader and Firstmember are the same"</error>
	<error>"First Member is already in a party"</error>
	<error>"First Member is already candidate of a party"</error>
	<error>"Invalid parameter type"</error>
	<related>Party</related>
	<relatedcfg>party.cfg</relatedcfg>
</function>

<function name="DisbandParty">
	<prototype>DisbandParty( PartyRef )</prototype>
	<parameter name="PartyRef" value="Party Reference" />
	<explain>Disbands the given Party</explain>
	<return>1 on success</return>
	<error>"Party has no leader"</error>
	<error>"Invalid parameter type"</error>
	<related>Party</related>
	<relatedcfg>party.cfg</relatedcfg>
</function>

<function name="SendPartyMsg">
	<prototype>SendPartyMsg( party, character, uctext )</prototype>
	<parameter name="party" value="Party Reference" />
	<parameter name="character" value="Character Reference" />
	<parameter name="uctext" value="Array of 2-byte integers, where each integer is a Unicode character" />	
	<explain>Sends a Party Message with character=Sender</explain>
	<return>1 on success</return>
	<error>"Unicode array exceeds maximum size."</error>
	<error>"Invalid value in Unicode array."</error>
	<error>"Invalid parameter type"</error>
	<related>Party</related>
	<related>Array</related>
	<relatedcfg>party.cfg</relatedcfg>
</function>

<function name="SendPrivatePartyMsg">
	<prototype>SendPrivatePartyMsg( party, character, tocharacter, uctext )</prototype>
	<parameter name="party" value="Party Reference" />
	<parameter name="character" value="Character Reference" />
	<parameter name="tocharacter" value="Character Reference" />
	<parameter name="uctext" value="Array of 2-byte integers, where each integer is a Unicode character" />	
	<explain>Sends a Private Party Message with character=Sender</explain>
	<return>1 on success</return>
	<error>"Unicode array exceeds maximum size."</error>
	<error>"Invalid value in Unicode array."</error>
	<error>"Invalid parameter type"</error>
	<related>Party</related>
	<related>Array</related>
	<relatedcfg>party.cfg</relatedcfg>
</function>

</ESCRIPT>

=== polserver/polserver/docs/docs.polserver.com/pol100/unicodeem.xml
<?xml version='1.0' encoding="iso-8859-1"?>
<?xml-stylesheet type="text/xsl" href="escript.xslt" ?>
<!DOCTYPE ESCRIPT SYSTEM "escript.dtd">
<ESCRIPT>  
  <fileheader fname="Unicode.em">
    <filedesc>Functions that allow messages to be sent to clients in any unicode language UO supports.</filedesc>
    <datemodified>02/10/2009</datemodified>
    <constant>const _DEFAULT_UCFONT  := 3;</constant>
    <constant>const _DEFAULT_UCCOLOR := 0x3B2;</constant>
    <constant>// Constants for PrintTextAbove*</constant>
    <constant>const JOURNAL_UC_PRINT_NAME    := 0x00; // Implicit.  Print's the object's description / npc's name in the journal.</constant>
    <constant>const JOURNAL_UC_PRINT_YOU_SEE := 0x01; // Will print "You see:" in the journal.</constant>
  </fileheader>
  
  <function name="BroadcastUC"> 
    <prototype>BroadcastUC(uc_text, langcode, font:=_DEFAULT_UCFONT, color:=_DEFAULT_UCCOLOR)</prototype>
    <parameter name="uc_text" value="Array of 2-byte integers, where each integer is a Unicode character" />
    <parameter name="langcode" value="3-character 'Originating Language' string code  e.g. ENU, CHT, DEU, RUS, KOR, etc." />
    <parameter name="font" value="Integer (optional) font code. Not the same as non-unicode font codes" />
    <parameter name="color" value="Integer (optional) color code. Not the same color as the same value for non-unicode prints" />
    <explain>Broadcasts a unicode string to all players</explain>
    <explain>uc_text MUST be an array of integers representing unicode characters.</explain>
    <explain>Integers must be "Big Endian" (0x1234) and not "Little Endian" (0x3412).</explain>
    <explain>Integers will be clipped internally to 2-bytes (value masked with 0xFFFF)</explain>
    <explain>The Array must be terminated with zero. (0x0000)</explain>
    <return>1 on success</return>
    <error>"Unicode array exceeds maximum size." (200 characters)</error>
    <error>"langcode must be a 3-character code."</error>
    <error>"Invalid value in Unicode array."</error>
    <error>"A parameter was invalid"</error>
    <related>Array</related>
  </function>

  <function name="PrintTextAboveUC"> 
    <prototype>PrintTextAboveUC(above_object, uc_text, langcode, font:=_DEFAULT_UCFONT, color:=_DEFAULT_UCCOLOR, journal_print := JOURNAL_UC_PRINT_NAME)</prototype>
    <parameter name="above_object" value="UObject reference" />
    <parameter name="uc_text" value="Array of 2-byte integers, where each integer is a Unicode character" />
    <parameter name="langcode" value="3-character 'Originating Language' string code  e.g. ENU, CHT, DEU, RUS, KOR, etc." />
    <parameter name="font" value="Integer (optional) font code. Not the same as non-unicode font codes" />
    <parameter name="color" value="Integer (optional) color code. Not the same color as the same value for non-unicode prints" />
    <parameter name="journal_print" value="Integer (optional)" />
    <explain>Displays a unicode string above 'above_object'</explain>
    <explain>uc_text MUST be an array of integers representing unicode characters.</explain>
    <explain>Integers must be "Big Endian" (0x1234) and not "Little Endian" (0x3412).</explain>
    <explain>Integers will be clipped internally to 2-bytes (value masked with 0xFFFF)</explain>
    <explain>The Array must be terminated with zero. (0x0000)</explain>
    <explain>Notes: journal_print flags:
<code>
const JOURNAL_UC_PRINT_NAME	:= 0x00; // Implicit.  Print's the object's description / npc's name in the journal.
const JOURNAL_UC_PRINT_YOU_SEE := 0x01; // Will print "You see:" in the journal.</code></explain>
    <return>1 on success, 0 on failure</return>
    <error>"Unicode array exceeds maximum size." (200 characters)</error>
    <error>"langcode must be a 3-character code."</error>
    <error>"Invalid value in Unicode array."</error>
    <error>"A parameter was invalid"</error>
    <related>Array</related>
    <related>UObject</related>
  </function>
  
  <function name="PrintTextAbovePrivateUC"> 
    <prototype>PrintTextAbovePrivateUC(above_object, uc_text, langcode, character, font:=_DEFAULT_UCFONT, color:=_DEFAULT_UCCOLOR, journal_print := JOURNAL_UC_PRINT_NAME)</prototype>
    <parameter name="above_object" value="UObject reference" />
    <parameter name="uc_text" value="Array of 2-byte integers, where each integer is a Unicode character" />
    <parameter name="langcode" value="3-character 'Originating Language' string code  e.g. ENU, CHT, DEU, RUS, KOR, etc." />
    <parameter name="character" value="Character reference to receive the text" />
    <parameter name="font" value="Integer (optional) font code. Not the same as non-unicode font codes" />
    <parameter name="color" value="Integer (optional) color code. Not the same color as the same value for non-unicode prints" />
    <parameter name="journal_print" value="Integer (optional)" />
    <explain>Displays a unicode string above 'above_object' only to 'character'</explain>
    <explain>uc_text MUST be an array of integers representing unicode characters.</explain>
    <explain>Integers must be "Big Endian" (0x1234) and not "Little Endian" (0x3412).</explain>
    <explain>Integers will be clipped internally to 2-bytes (value masked with 0xFFFF)</explain>
    <explain>The Array must be terminated with zero. (0x0000)</explain>
    <explain>Notes: journal_print flags:
<code>
const JOURNAL_UC_PRINT_NAME	:= 0x00; // Implicit.  Print's the object's description / npc's name in the journal.
const JOURNAL_UC_PRINT_YOU_SEE := 0x01; // Will print "You see:" in the journal.</code></explain>
    <return>1 on success, 0 on failure</return>
    <error>"Unicode array exceeds maximum size." (200 characters)</error>
    <error>"langcode must be a 3-character code."</error>
    <error>"Invalid value in Unicode array."</error>
    <error>"A parameter was invalid"</error>
    <related>Array</related>
    <related>UObject</related>
    <related>Character</related>
  </function>
  
  <function name="SendSysMessageUC"> 
    <prototype>SendSysMessageUC(character, uc_text, langcode, font:=_DEFAULT_UCFONT, color:=_DEFAULT_UCCOLOR)</prototype>
    <parameter name="character" value="Character reference to receive the text" />
    <parameter name="uc_text" value="Array of 2-byte integers, where each integer is a Unicode character" />
    <parameter name="langcode" value="3-character 'Originating Language' string code  e.g. ENU, CHT, DEU, RUS, KOR, etc." />
    <parameter name="font" value="Integer (optional) font code. Not the same as non-unicode font codes" />
    <parameter name="color" value="Integer (optional) color code. Not the same color as the same value for non-unicode prints" />
    <explain>Displays a unicode system message to 'character'</explain>
    <explain>uc_text MUST be an array of integers representing unicode characters.</explain>
    <explain>Integers must be "Big Endian" (0x1234) and not "Little Endian" (0x3412).</explain>
    <explain>Integers will be clipped internally to 2-bytes (value masked with 0xFFFF)</explain>
    <explain>The Array must be terminated with zero. (0x0000)</explain>
    <return>1 on success</return>
    <error>"Unicode array exceeds maximum size." (200 characters)</error>
    <error>"langcode must be a 3-character code."</error>
    <error>"Invalid value in Unicode array."</error>
    <error>"A parameter was invalid"</error>
    <related>Array</related>
  </function>

  <function name="RequestInputUC"> 
    <prototype>RequestInputUC(character, item, uc_prompt, langcode)</prototype>
    <parameter name="character" value="Character reference to receive the text" />
    <parameter name="item" value="placeholder, pass any valid item" />
    <parameter name="uc_prompt" value="Array of 2-byte integers, where each integer is a Unicode character. The question to which the player types the response." />
    <parameter name="langcode" value="3-character 'Originating Language' string code  e.g. ENU, CHT, DEU, RUS, KOR, etc." />
    <explain>Displays a unicode system message prompt to 'character', the character can then enter unicode characters which will be returned to the script.</explain>
    <explain>uc_prompt MUST be an array of integers representing unicode characters.</explain>
    <explain>Integers must be "Big Endian" (0x1234) and not "Little Endian" (0x3412).</explain>
    <explain>Integers will be clipped internally to 2-bytes (value masked with 0xFFFF)</explain>
    <explain>The Array must be terminated with zero. (0x0000)</explain>
    <return>a struct with members "lang" (3-character string), and "uc_text" (a "unicode array" of 2-byte integers representing unicode characters in the specified language) on success.</return>
    <error>"No client attached"</error>
    <error>"Another script has an active prompt"</error>
    <error>"Unicode array exceeds maximum size." (200 characters)</error>
    <error>"langcode must be a 3-character code."</error>
    <error>"Invalid value in Unicode array."</error>
    <error>"Invalid control characters in text entry"</error>
    <error>"A parameter was invalid"</error>
    <related>Array</related>
  </function>

</ESCRIPT>

=== polserver/polserver/tags/R2013-09-03_099/docs/docs.polserver.com/pol099/utilem.xml
<?xml version='1.0' encoding="iso-8859-1"?>
<?xml-stylesheet type="text/xsl" href="escript.xslt" ?>
<!DOCTYPE ESCRIPT SYSTEM "escript.dtd">
<ESCRIPT>
  <fileheader fname="Util.em">
    <filedesc>Utility functions</filedesc>
    <datemodified>08/02/2010</datemodified>
  </fileheader>
    
  <function name="RandomInt"> 
    <prototype>RandomInt(integer below_this_number)</prototype>
    <parameter name="below_this_number" value="Integer" />
    <explain>Returns a random integer below the passed parameter and greater or equal to zero.</explain>
    <return>Integer R such that 0 less or equal to R less than below_this_number</return>
	<error>"RandomInt() expects a positive integer"</error>
  </function>

  <function name="RandomIntMinMax"> 
    <prototype>RandomIntMinMax(integer min_integer, integer max_integer)</prototype>
    <parameter name="min_integer" value="Integer" />
    <parameter name="max_integer" value="Integer" />
    <explain>Returns a random integer between the Min and Max integers passed. Accepts negative Integers and if parameters in wrong order swaps them.</explain>
    <return>Integer Randomly between Min and Max parameters</return>
	<error>"RandomIntMinMax() expects an integer"</error>
  </function>

  <function name="RandomFloat"> 
    <prototype>RandomFloat(real below_this_number)</prototype>
    <parameter name="below_this_number" value="Real" />
    <explain>Returns a random real below the passed parameter and greater or equal to zero.</explain>
    <return>Real R such that 0 less or equal to R less than below_this_number</return>
	<error>"RandomFloat() expects a Real parameter"</error>
  </function>

  <function name="RandomDiceRoll"> 
    <prototype>RandomDiceRoll(String dice_string)</prototype>
    <parameter name="dice_string" value="String" />
    <explain>Returns a random number according to the passed die roll string. This is standard NdS+X format. N=number of dies to roll, S=number of sides per die, X=integer to add(or subtract) after roll.</explain>
    <explain>Here's some acceptable examples:
<code>
4
d4
d6+6
d6-2
2d12
2d8+12
2d8-4
</code></explain>
    <return>Valkyrie's pedantic wording: "returns an integer greater or equal to N+X and not more than N*S+X"</return>
  </function>

  <function name="StrFormatTime"> 
    <prototype>StrFormatTime( format_string, time_stamp:=0 )</prototype>
    <parameter name="format_string" value="String" />
    <parameter name="time_stamp" value="Integer" />
    <explain>Takes in the StrFTime() specifiers for the format string.</explain>
    <explain>If time_stamp is 0, it will use POLCore().systime.</explain>
    <explain>For format_string information, please go to http://www.cppreference.com/stddate/strftime.html</explain>
    <return>String</return>
    <error>"No time string passed."</error>
    <error>"Format string exceeded 100 characters."</error>
  </function>

</ESCRIPT>

=== polserver/polserver/docs/docs.polserver.com/pol100/basicioem.xml
<?xml version='1.0' encoding="iso-8859-1"?>
<?xml-stylesheet type="text/xsl" href="escript.xslt" ?>
<!DOCTYPE ESCRIPT SYSTEM "escript.dtd">
<ESCRIPT>  
  <fileheader fname="basicio.em">
    <filedesc>Basic I/O functions.</filedesc>
    <datemodified>08/31/2015</datemodified>
  </fileheader>

  <function name="Print">
    <prototype>Print(anything)</prototype>
    <parameter name="anything" value="Any object, or primitive." />
    <explain>
      Prints 'anything' to the console. If it's a string or number, it will show the value. If it's an array, struct or dictionary, it will show the contents of the structure fairly nicely. On Packets it will show the content. Else, it shows the type of object, i.e. 'ItemRef'.
    </explain>
    <return>Nothing</return>
 </function>
  
</ESCRIPT>
