=== polserver/polserver/docs/docs.polserver.com/pol100/objref.dtd
<!ENTITY % XHTML1-strict PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "https://www.w3.org/TR/html4/strict.dtd">

<!ELEMENT ESCRIPT (fileheader,class*)>
<!ELEMENT fileheader (header,datemodified)>
  <!ELEMENT header (#PCDATA)>
  <!ELEMENT datemodified (#PCDATA)>
<!ELEMENT class (parent?, child*, explain*, member*, method*)>
  <!ATTLIST class name CDATA #REQUIRED>
  <!ELEMENT parent (#PCDATA)>
  <!ELEMENT child (#PCDATA)>
  <!ELEMENT explain (#PCDATA)>
  <!ELEMENT member (#PCDATA | %XHTML1-strict;)*>
  <!ATTLIST member mname CDATA #REQUIRED>
  <!ATTLIST member type CDATA #REQUIRED>
  <!ATTLIST member access CDATA #REQUIRED>
  <!ELEMENT method (#PCDATA | %XHTML1-strict;)*>
  <!ATTLIST method proto CDATA #REQUIRED>
  <!ATTLIST method returns CDATA #REQUIRED>

=== polserver/polserver/docs/docs.polserver.com/pol100/objref.xml
<?xml version='1.0' encoding="iso-8859-1"?>
<?xml-stylesheet type="text/xsl" href="objref.xslt" ?>
<!DOCTYPE ESCRIPT SYSTEM "objref.dtd">
<ESCRIPT>
<!--
	Notes for updating this file (as of 08/31/2015):
	* The almost complete list of object properties that are exposed to scripts is located
	  in pol-core/bscript/parser.cpp, defined as ObjMember object_members[], look for MBR_* constants
	  From there, you have to determine which members are implemented on which objects... DO NOT TRUST THE COMMENTS.
	* The source code doesn't have many comments, but core-changes contains a detailed description for every mod.
	* The objects' properties are then handled in pol-core/pol/uoscrobj.cpp, look for MBR_* constants,
	  every script object then has its own namespace. Sometimes the definitions are straight into the object's
	  main file. Look for methods called get_script_member_id() and set_script_member_id(). Some simple classes
	  like Package even bypass all of this and just implement get_member() method directly with property names
	  hardcoded into the if block.
	* The object methods are usually MTH_* constants and are handled in call_method_id(), script_method_id() or
	  directly call_method(), script_method() methods. They are also almost all defined in
	  pol-core/bscript/parser.cpp as ObjMethod object_methods[], the rest of the methods follows the same hardcode
	  logic as the properties in the "minor" objects.
	* Hint: the PHP parser will sort entries alphabetically, try to keep this file in the same order that you will
	  find definitions on the source files: it will be easier to maintain.

	Last full review and sync with the code: 08/31/2015 by Bodom... it's a long job, please try to keep this in sync :)
-->
<fileheader>
<header>Class Hierarchy</header>
<!-- objref.svg will be inserted here -->
<!-- todo automate updating this? -->
<datemodified>07/24/2026</datemodified>
</fileheader>


<class name="UObject">
<child>Character</child>
<child>Item</child>
<explain>The base UO Object class</explain>
<member mname="x" type="Integer" access="r/o">x coordinate</member>
<member mname="y" type="Integer" access="r/o">y coordinate</member>
<member mname="z" type="Integer" access="r/o">z coordinate</member>
<member mname="realm" type="String" access="r/o">case-sensitive name of the realm</member>
<member mname="name" type="String" access="r/w">name string (for items use .desc for single-click text, this does not include suffix or formatting)</member>
<member mname="objtype" type="Integer" access="r/o">object type as defined in itemdesc.cfg</member>
<member mname="graphic" type="Integer" access="r/w">art id number</member>
<member mname="serial" type="Integer" access="r/o">unique object identifier</member>
<member mname="color" type="Integer" access="r/w">color value (0 to 0xFFF)</member>
<member mname="facing" type="Integer" access="r/w">facing or the object (meaningful for mobiles and light-emitting items) range 0-127</member>
<member mname="height" type="Integer" access="r/o">height of the graphic as defined in tiledata.mul</member>
<member mname="dirty" type="Boolean" access="r/o">This is set when anything on the object changes, and cleared on world save</member>
<member mname="weight" type="Integer" access="r/o">weight of the graphic as defined in tiledata.mul</member>
<member mname="multi" type="Multi" access="r/o">MultiRef for the Multi the object is on</member>
<member mname="specific_name" type="Boolean" access="r/o">Set if a specific name is set, otherwise like itemdesc name false.</member>

<method proto="propnames()" returns="Array">Returns an array of property name strings.</method>
<method proto="isa(POLCLASS_*)" returns="boolean">True if the derived class is the same as the passed class type (see uo.em for all constants)</method>
<method proto="getprop(string propname)" returns="script object/error">Returns an unpacked script object (i.e. int,string,array,etc)</method>
<method proto="setprop(string propname, object propval)" returns="true/error">Sets a packable object to a property.</method>
<method proto="eraseprop(string propname)" returns="true/error">Erases the property named 'propname'.</method>
<method proto="set_member(string membername, obj value)" returns="object, new value of member or error">Sets the built-in member 'membername' to 'value'. obj.set_member("name","Eric") is the same as obj.name := "Eric"</method>
<method proto="get_member(string membername)" returns="object, value of member or error">Gets the value of the built-in member 'membername'. var objname := obj.get_member("name") is the same as var objname := obj.name</method>
</class>


<class name="Item">
<parent>UObject</parent>
<child>Equipment</child>
<child>Lockable</child>
<child>Map</child>
<child>Multi</child>
<explain>Represents a physical item in the world.</explain>
<member mname="amount" type="Integer" access="r/o">stack size</member>
<member mname="layer" type="Integer" access="r/o">equipment layer</member>
<member mname="container" type="Item" access="r/o">item contained in</member>
<member mname="usescript" type="String" access="r/w">double-click action script. set to empty string for itemdesc.cfg default script.</member>
<member mname="equipscript" type="String" access="r/w">script run when item equipped on a character</member>
<member mname="unequipscript" type="String" access="r/w">script run when item unequipped</member>
<member mname="desc" type="String" access="r/o">single click description string (formatted name and suffix added to it without formatting if it exists)</member>
<member mname="movable" type="Boolean" access="r/w">true if player may move the item</member>
<member mname="invisible" type="Boolean" access="r/w">true if the item is invisible</member>
<member mname="decayat" type="Integer" access="r/w">game clock value after which this item might decay. 0=do not decay</member>
<member mname="sellprice" type="Integer" access="r/w">Amount of gold an NPC sells this item for. 0=not for sale, -1=itemdesc default.</member>
<member mname="buyprice" type="Integer" access="r/w">Amount of gold an NPC buys this item for. 0=not for sale, -1=itemdesc default.</member>
<member mname="newbie" type="Boolean" access="r/w">true if the item remains with the ghost when player dies</member>
<member mname="insured" type="Boolean" access="r/w">like newbie, but it gets reset to 0 whenever it saves an item from dropping</member>
<member mname="cursed" type="Boolean" access="r/w">true if item is cursed; does not have any special core handling other than preventing cursed and non-cursed items from stacking together.</member>
<member mname="item_count" type="Integer" access="r/o">number of items in container including the container itself (1 if this item is not a container or an empty container)</member>
<member mname="stackable" type="Integer" access="r/o">return is based on POL Decided stackability of item.</member>
<member mname="tile_layer" type="Integer" access="r/o">returns the Layer setting in the Tiles.cfg/Tiledata</member>
<member mname="resist_fire" type="Integer" access="r/o">Total AOS+ armor factor.</member>
<member mname="resist_cold" type="Integer" access="r/o">Total AOS+ armor factor.</member>
<member mname="resist_energy" type="Integer" access="r/o">Total AOS+ armor factor.</member>
<member mname="resist_poison" type="Integer" access="r/o">Total AOS+ armor factor.</member>
<member mname="resist_physical" type="Integer" access="r/o">Total AOS+ armor factor.</member>
<member mname="resist_fire_mod" type="Integer" access="r/w">AOS+ Armor factor modifier</member>
<member mname="resist_cold_mod" type="Integer" access="r/w">AOS+ Armor factor modifier</member>
<member mname="resist_energy_mod" type="Integer" access="r/w">AOS+ Armor factor modifier</member>
<member mname="resist_poison_mod" type="Integer" access="r/w">AOS+ Armor factor modifier</member>
<member mname="resist_physical_mod" type="Integer" access="r/w">AOS+ Armor factor modifier</member>
<member mname="saveonexit" type="Boolean" access="r/w">default 1, if you set this to 0 the item and (if container, it's contents) will NOT be saved to datafile</member>
<member mname="damage_fire" type="Integer" access="r/o">Total AOS+ damage factor.</member>
<member mname="damage_cold" type="Integer" access="r/o">Total AOS+ damage factor.</member>
<member mname="damage_energy" type="Integer" access="r/o">Total AOS+ damage factor.</member>
<member mname="damage_poison" type="Integer" access="r/o">Total AOS+ damage factor.</member>
<member mname="damage_physical" type="Integer" access="r/o">Total AOS+ damage factor.</member>
<member mname="damage_fire_mod" type="Integer" access="r/w">AOS+ damage modifier</member>
<member mname="damage_cold_mod" type="Integer" access="r/w">AOS+ damage modifier</member>
<member mname="damage_energy_mod" type="Integer" access="r/w">AOS+ damage modifier</member>
<member mname="damage_poison_mod" type="Integer" access="r/w">AOS+ damage modifier</member>
<member mname="damage_physical_mod" type="Integer" access="r/w">AOS+ damage modifier</member>
<member mname="getgottenby" type="Character" access="r/o">Returns CharRef of Player holding item, Error if not being held</member>
<member mname="process" type="Script" access="r/o">Control script reference, error on none</member>
<member mname="doubleclickrange" type="Integer" access="r/o">Max distance for using this item</member>
<member mname="quality" type="Double" access="r/w">1.0=Average and default</member>
<member mname="hp" type="Integer" access="r/w">Hit points of item</member>
<member mname="maxhp_mod" type="Integer" access="r/w">Maximum Hit Point modification</member>
<member mname="maxhp" type="Integer" access="r/o">Maximum Hit Points of item</member>
<member mname="name_suffix" type="String" access="r/w">For adding crafter marks or such, will be appended to desc</member>
<member mname="house" type="House" access="r/o">Returns a reference to the House this item is component of, if any</member>
